// Real-feel artist directory data — mix of idols, actors, producers.
window.ARTISTS = [
  // K-POP IDOLS — Female
  { name: "Jennie", hangul: "제니", group: "BLACKPINK", type: "Idol", gender: "F", agency: "ODD ATELIER", gen: "3", debut: 2016, active: true, top: true, born: 1996 },
  { name: "Lisa", hangul: "리사", group: "BLACKPINK", type: "Idol", gender: "F", agency: "LLOUD", gen: "3", debut: 2016, active: true, top: true, born: 1997 },
  { name: "Jisoo", hangul: "지수", group: "BLACKPINK", type: "Idol", gender: "F", agency: "BLISSOO", gen: "3", debut: 2016, active: true, top: true, born: 1995 },
  { name: "Rosé", hangul: "로제", group: "BLACKPINK", type: "Idol", gender: "F", agency: "Atlantic", gen: "3", debut: 2016, active: true, top: true, born: 1997 },
  { name: "IU", hangul: "아이유", group: "—", type: "Solista", gender: "F", agency: "EDAM", gen: "2", debut: 2008, active: true, top: true, born: 1993 },
  { name: "Hanni", hangul: "하니", group: "NewJeans", type: "Idol", gender: "F", agency: "ADOR", gen: "4", debut: 2022, active: true, top: true, born: 2004 },
  { name: "Minji", hangul: "민지", group: "NewJeans", type: "Idol", gender: "F", agency: "ADOR", gen: "4", debut: 2022, active: true, born: 2004 },
  { name: "Haerin", hangul: "해린", group: "NewJeans", type: "Idol", gender: "F", agency: "ADOR", gen: "4", debut: 2022, active: true, born: 2006 },
  { name: "Danielle", hangul: "다니엘", group: "NewJeans", type: "Idol", gender: "F", agency: "ADOR", gen: "4", debut: 2022, active: true, born: 2005 },
  { name: "Hyein", hangul: "혜인", group: "NewJeans", type: "Idol", gender: "F", agency: "ADOR", gen: "4", debut: 2022, active: true, born: 2008 },
  { name: "Karina", hangul: "카리나", group: "aespa", type: "Idol", gender: "F", agency: "SM", gen: "4", debut: 2020, active: true, top: true, born: 2000 },
  { name: "Winter", hangul: "윈터", group: "aespa", type: "Idol", gender: "F", agency: "SM", gen: "4", debut: 2020, active: true, born: 2001 },
  { name: "Giselle", hangul: "지젤", group: "aespa", type: "Idol", gender: "F", agency: "SM", gen: "4", debut: 2020, active: true, born: 2000 },
  { name: "Ningning", hangul: "닝닝", group: "aespa", type: "Idol", gender: "F", agency: "SM", gen: "4", debut: 2020, active: true, born: 2002 },
  { name: "Sakura", hangul: "사쿠라", group: "LE SSERAFIM", type: "Idol", gender: "F", agency: "Source Music", gen: "4", debut: 2022, active: true, born: 1998 },
  { name: "Chaewon", hangul: "채원", group: "LE SSERAFIM", type: "Idol", gender: "F", agency: "Source Music", gen: "4", debut: 2022, active: true, born: 2000 },
  { name: "Minnie", hangul: "민니", group: "(G)I-DLE", type: "Idol", gender: "F", agency: "Cube", gen: "3", debut: 2018, active: true, born: 1997 },
  { name: "Soyeon", hangul: "소연", group: "(G)I-DLE", type: "Idol", gender: "F", agency: "Cube", gen: "3", debut: 2018, active: true, top: true, born: 1998 },
  { name: "Yuqi", hangul: "우기", group: "(G)I-DLE", type: "Idol", gender: "F", agency: "Cube", gen: "3", debut: 2018, active: true, born: 1999 },
  { name: "Wonyoung", hangul: "원영", group: "IVE", type: "Idol", gender: "F", agency: "Starship", gen: "4", debut: 2021, active: true, top: true, born: 2004 },
  { name: "Yujin", hangul: "유진", group: "IVE", type: "Idol", gender: "F", agency: "Starship", gen: "4", debut: 2021, active: true, born: 2003 },
  { name: "Nayeon", hangul: "나연", group: "TWICE", type: "Idol", gender: "F", agency: "JYP", gen: "3", debut: 2015, active: true, born: 1995 },
  { name: "Mina", hangul: "미나", group: "TWICE", type: "Idol", gender: "F", agency: "JYP", gen: "3", debut: 2015, active: true, born: 1997 },
  { name: "Tzuyu", hangul: "쯔위", group: "TWICE", type: "Idol", gender: "F", agency: "JYP", gen: "3", debut: 2015, active: true, born: 1999 },
  { name: "Suzy", hangul: "수지", group: "ex-Miss A", type: "Atriz/Idol", gender: "F", agency: "Mgmt SOOP", gen: "2", debut: 2010, active: true, top: true, born: 1994 },
  { name: "Taeyeon", hangul: "태연", group: "Girls' Generation", type: "Idol", gender: "F", agency: "SM", gen: "2", debut: 2007, active: true, top: true, born: 1989 },
  { name: "Yoona", hangul: "윤아", group: "Girls' Generation", type: "Atriz/Idol", gender: "F", agency: "SM", gen: "2", debut: 2007, active: true, born: 1990 },

  // K-POP IDOLS — Male
  { name: "RM", hangul: "RM", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, top: true, born: 1994 },
  { name: "Jin", hangul: "진", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, born: 1992 },
  { name: "Suga", hangul: "슈가", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, born: 1993 },
  { name: "J-Hope", hangul: "제이홉", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, born: 1994 },
  { name: "Jimin", hangul: "지민", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, top: true, born: 1995 },
  { name: "V", hangul: "뷔", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, top: true, born: 1995 },
  { name: "Jungkook", hangul: "정국", group: "BTS", type: "Idol", gender: "M", agency: "HYBE", gen: "3", debut: 2013, active: true, top: true, born: 1997 },
  { name: "Jinwoo", hangul: "진우", group: "WINNER", type: "Idol", gender: "M", agency: "YG", gen: "2", debut: 2014, active: true, born: 1991 },
  { name: "Mingyu", hangul: "민규", group: "SEVENTEEN", type: "Idol", gender: "M", agency: "PLEDIS", gen: "3", debut: 2015, active: true, born: 1997 },
  { name: "Wonwoo", hangul: "원우", group: "SEVENTEEN", type: "Idol", gender: "M", agency: "PLEDIS", gen: "3", debut: 2015, active: true, born: 1996 },
  { name: "Heeseung", hangul: "희승", group: "ENHYPEN", type: "Idol", gender: "M", agency: "HYBE", gen: "4", debut: 2020, active: true, born: 2001 },
  { name: "Jay", hangul: "제이", group: "ENHYPEN", type: "Idol", gender: "M", agency: "HYBE", gen: "4", debut: 2020, active: true, born: 2002 },
  { name: "Mark", hangul: "마크", group: "NCT", type: "Idol", gender: "M", agency: "SM", gen: "3", debut: 2016, active: true, born: 1999 },
  { name: "Taeyong", hangul: "태용", group: "NCT", type: "Idol", gender: "M", agency: "SM", gen: "3", debut: 2016, active: true, born: 1995 },
  { name: "Jeon Woong", hangul: "전웅", group: "AB6IX", type: "Idol", gender: "M", agency: "Brand New", gen: "4", debut: 2019, active: true, born: 1999 },
  { name: "G-Dragon", hangul: "지드래곤", group: "BIGBANG", type: "Idol", gender: "M", agency: "Galaxy Corp", gen: "2", debut: 2006, active: true, top: true, born: 1988 },
  { name: "T.O.P", hangul: "탑", group: "BIGBANG", type: "Idol", gender: "M", agency: "—", gen: "2", debut: 2006, active: false, born: 1987 },
  { name: "Zion.T", hangul: "자이언티", group: "—", type: "Solista", gender: "M", agency: "The Black Label", gen: "2", debut: 2013, active: true, born: 1989 },

  // ACTORS — Male
  { name: "Kim Soo-hyun", hangul: "김수현", group: "—", type: "Ator", gender: "M", agency: "Gold Medalist", gen: "—", debut: 2007, active: true, top: true, born: 1988 },
  { name: "Lee Jong-suk", hangul: "이종석", group: "—", type: "Ator", gender: "M", agency: "A-MAN", gen: "—", debut: 2010, active: true, top: true, born: 1989 },
  { name: "Gong Yoo", hangul: "공유", group: "—", type: "Ator", gender: "M", agency: "Management SOOP", gen: "—", debut: 2001, active: true, top: true, born: 1979 },
  { name: "Hyun Bin", hangul: "현빈", group: "—", type: "Ator", gender: "M", agency: "VAST", gen: "—", debut: 2003, active: true, top: true, born: 1982 },
  { name: "Lee Min-ho", hangul: "이민호", group: "—", type: "Ator", gender: "M", agency: "MYM", gen: "—", debut: 2006, active: true, top: true, born: 1987 },
  { name: "Park Seo-joon", hangul: "박서준", group: "—", type: "Ator", gender: "M", agency: "Awesome", gen: "—", debut: 2011, active: true, born: 1988 },
  { name: "Park Bo-gum", hangul: "박보검", group: "—", type: "Ator", gender: "M", agency: "Blossom", gen: "—", debut: 2011, active: true, top: true, born: 1993 },
  { name: "Jung Hae-in", hangul: "정해인", group: "—", type: "Ator", gender: "M", agency: "FN", gen: "—", debut: 2013, active: true, born: 1988 },
  { name: "Lee Do-hyun", hangul: "이도현", group: "—", type: "Ator", gender: "M", agency: "Yuehua", gen: "—", debut: 2017, active: true, born: 1995 },
  { name: "Byeon Woo-seok", hangul: "변우석", group: "—", type: "Ator", gender: "M", agency: "Varo", gen: "—", debut: 2016, active: true, born: 1991 },
  { name: "Lee Je-hoon", hangul: "이제훈", group: "—", type: "Ator", gender: "M", agency: "Company on", gen: "—", debut: 2006, active: true, born: 1984 },
  { name: "Lee Hyo-je", hangul: "이효제", group: "—", type: "Ator", gender: "M", agency: "—", gen: "—", debut: 2018, active: true, born: 1996 },
  { name: "Kang Seok-woo", hangul: "강석우", group: "—", type: "Ator", gender: "M", agency: "—", gen: "—", debut: 1980, active: true, born: 1957 },
  { name: "Jeon Geon-hu", hangul: "전건후", group: "—", type: "Ator", gender: "M", agency: "—", gen: "—", debut: 2022, active: true, born: 1999 },
  { name: "So Ji-sub", hangul: "소지섭", group: "—", type: "Ator", gender: "M", agency: "Company SOOP", gen: "—", debut: 1995, active: true, born: 1977 },

  // ACTRESSES — Female
  { name: "Kim Ji-won", hangul: "김지원", group: "—", type: "Atriz", gender: "F", agency: "—", gen: "—", debut: 2008, active: true, top: true, born: 1992 },
  { name: "Son Ye-jin", hangul: "손예진", group: "—", type: "Atriz", gender: "F", agency: "MSteam", gen: "—", debut: 2001, active: true, top: true, born: 1982 },
  { name: "Jun Ji-hyun", hangul: "전지현", group: "—", type: "Atriz", gender: "F", agency: "Echo Global", gen: "—", debut: 1997, active: true, top: true, born: 1981 },
  { name: "Park Bo-young", hangul: "박보영", group: "—", type: "Atriz", gender: "F", agency: "BH", gen: "—", debut: 2006, active: true, top: true, born: 1990 },
  { name: "Park Shin-hye", hangul: "박신혜", group: "—", type: "Atriz", gender: "F", agency: "SALT", gen: "—", debut: 2003, active: true, born: 1990 },
  { name: "Seo Ye-ji", hangul: "서예지", group: "—", type: "Atriz", gender: "F", agency: "—", gen: "—", debut: 2013, active: true, born: 1990 },
  { name: "Bae Suzy", hangul: "수지", group: "—", type: "Atriz", gender: "F", agency: "Mgmt SOOP", gen: "—", debut: 2010, active: true, top: true, born: 1994 },
  { name: "Kim Tae-ri", hangul: "김태리", group: "—", type: "Atriz", gender: "F", agency: "Management mmm", gen: "—", debut: 2014, active: true, born: 1990 },
  { name: "Han So-hee", hangul: "한소희", group: "—", type: "Atriz", gender: "F", agency: "9ato", gen: "—", debut: 2017, active: true, top: true, born: 1994 },
  { name: "Kim Go-eun", hangul: "김고은", group: "—", type: "Atriz", gender: "F", agency: "BH", gen: "—", debut: 2012, active: true, born: 1991 },
  { name: "Kim Hye-soo", hangul: "김혜수", group: "—", type: "Atriz", gender: "F", agency: "—", gen: "—", debut: 1986, active: true, born: 1970 },
  { name: "Jang Shin-young", hangul: "장신영", group: "—", type: "Atriz", gender: "F", agency: "—", gen: "—", debut: 2002, active: true, born: 1984 },
  { name: "Song Hye-kyo", hangul: "송혜교", group: "—", type: "Atriz", gender: "F", agency: "UAA", gen: "—", debut: 1996, active: true, top: true, born: 1981 },
];

// Letter counts (simulated to feel like 1000+ catalog)
window.LETTER_COUNTS = {
  A: 32, B: 47, C: 78, D: 24, E: 19, F: 4, G: 53, H: 89, I: 21, J: 142,
  K: 168, L: 124, M: 58, N: 39, O: 18, P: 96, Q: 2, R: 14, S: 132,
  T: 41, U: 9, V: 6, W: 18, X: 1, Y: 71, Z: 12,
};

window.AGENCIES_TOP = [
  { name: "HYBE", count: 87 }, { name: "SM Entertainment", count: 64 },
  { name: "JYP", count: 51 }, { name: "YG", count: 38 },
  { name: "Starship", count: 24 }, { name: "Cube", count: 19 },
  { name: "PLEDIS", count: 22 }, { name: "ADOR", count: 5 },
];
