/**
 * Seed QuizQuestion table — batch 2 (100 new questions).
 * Run: DATABASE_URL=... npx tsx scripts/seed-quiz-questions-batch2.ts
 */
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://hallyuhub:hallyuhub@127.0.0.1:5433/hallyuhub_production',
})
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) as any })

const questions = [
  // ─── K-Pop ────────────────────────────────────────────────────────────────
  {
    question: 'Qual é o nome do integrante do BTS conhecido pelo seu álbum solo "Indigo"?',
    options: ['Suga', 'J-Hope', 'RM', 'Jin'],
    correct: 2,
    explanation: '"Indigo" (2022) é o primeiro álbum solo de RM (Kim Namjoon), líder e rapper do BTS.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual foi o primeiro grupo de K-Pop masculino a se apresentar no Coachella?',
    options: ['BTS', 'EXO', '2NE1', 'BIGBANG'],
    correct: 0,
    explanation: 'O BTS se apresentou no Coachella em 2019 como atração surpresa, tornando-se o primeiro grupo masculino de K-Pop no festival.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo foi formado pelo reality show "Produce 101" da Mnet em 2016?',
    options: ['WANNA ONE', 'IOI', 'IZ*ONE', 'X1'],
    correct: 1,
    explanation: 'O IOI (I.O.I) foi formado pela primeira temporada do Produce 101 em 2016, com 11 membros selecionados pelo público.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Em que ano o grupo EXO fez sua estreia?',
    options: ['2010', '2011', '2012', '2013'],
    correct: 2,
    explanation: 'O EXO estreou em abril de 2012 pela SM Entertainment, inicialmente dividido em EXO-K e EXO-M.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual membro do BTS é conhecido pelo apelido "Worldwide Handsome"?',
    options: ['V', 'Jimin', 'Jin', 'Jungkook'],
    correct: 2,
    explanation: 'Jin (Kim Seokjin) ficou famoso pelo apelido "Worldwide Handsome", que ele mesmo cunhou em entrevistas com humor.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo de K-Pop foi o primeiro a ganhar um Grammy Award?',
    options: ['BTS', 'EXO', 'BLACKPINK', 'Nenhum grupo ganhou ainda'],
    correct: 3,
    explanation: 'Até 2024, nenhum grupo de K-Pop ganhou um Grammy Award, embora o BTS e outros tenham sido indicados ou se apresentado na cerimônia.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome do conceito de "máquina de fãs" explorado pela SM Entertainment com grupos como NCT?',
    options: ['Infinite Expansion', 'Neo Culture Technology', 'Universe System', 'Unit Concept'],
    correct: 1,
    explanation: 'NCT significa "Neo Culture Technology" — o conceito da SM permite membros rotativos e unidades ilimitadas.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Qual artista feminina de K-Pop lançou o álbum "MOTO" em 2023 como solo?',
    options: ['Lisa', 'Rosé', 'Jennie', 'Jisoo'],
    correct: 3,
    explanation: 'Jisoo do BLACKPINK lançou "ME", seu primeiro EP solo, em março de 2023, com o single "Flower".',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Quantos membros tem o grupo SEVENTEEN?',
    options: ['12', '13', '14', '17'],
    correct: 1,
    explanation: 'O SEVENTEEN tem 13 membros, divididos em 3 unidades: Hip-Hop, Performance e Vocal. O nome "17" representa 13 membros + 3 unidades + 1 coração.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual música do Psy se tornou o vídeo mais visto do YouTube por um tempo em 2012?',
    options: ['Gentleman', 'Hangover', 'Gangnam Style', 'Daddy'],
    correct: 2,
    explanation: '"Gangnam Style" de Psy foi lançada em julho de 2012 e se tornou o primeiro vídeo a atingir 1 bilhão de views no YouTube.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo feminino lançou o álbum "The Album" em outubro de 2020?',
    options: ['TWICE', 'Red Velvet', 'BLACKPINK', 'aespa'],
    correct: 2,
    explanation: '"The Album" foi o primeiro álbum de estúdio completo do BLACKPINK, lançado em outubro de 2020.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome do fandom oficial do TWICE?',
    options: ['ONCE', 'TWICE-L', 'Candy', 'Candybong'],
    correct: 0,
    explanation: 'O fandom do TWICE se chama ONCE — porque se você ouvir TWICE uma vez (once), você vai se apaixonar.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo de 4ª geração do K-Pop é conhecido por um universo de personagens chamado "SMCU"?',
    options: ['Stray Kids', 'aespa', 'ATEEZ', 'TXT'],
    correct: 1,
    explanation: 'aespa tem um universo de ficção científica chamado SM Culture Universe (SMCU), onde versões virtuais das integrantes interagem com as reais.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Qual rapper de K-Pop lançou o aclamado mixtape "Agust D" em 2016?',
    options: ['RM', 'G-Dragon', 'Suga', 'Zico'],
    correct: 2,
    explanation: 'Suga do BTS lançou o mixtape "Agust D" gratuitamente em 2016 sob o pseudônimo Agust D, recebendo elogios da crítica.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual foi o grupo precursor que influenciou a maioria dos grupos de K-Pop modernos, ativo nos anos 90?',
    options: ['H.O.T', 'Sechs Kies', 'g.o.d', 'S.E.S'],
    correct: 0,
    explanation: 'H.O.T (High Five of Teenagers), estreando em 1996 pela SM Entertainment, é considerado o primeiro grupo de K-Pop moderno e influenciou toda a indústria.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Qual grupo lançou o hit "Miroh" e é conhecido por sua energia intensa de "stay"?',
    options: ['ATEEZ', 'Stray Kids', 'MONSTA X', 'GOT7'],
    correct: 1,
    explanation: '"Miroh" (2019) é um dos maiores hits do Stray Kids. O fandom deles se chama STAY.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual integrante do BIGBANG é considerado um dos maiores compositores do K-Pop e tem o apelido "King of K-Pop"?',
    options: ['T.O.P', 'Taeyang', 'G-Dragon', 'Daesung'],
    correct: 2,
    explanation: 'G-Dragon (Kwon Jiyong) é amplamente reconhecido como o "King of K-Pop" por sua influência criativa como compositor, produtor e trendsetter de moda.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo feminino, conhecido pelo hit "Lovesick Girls", é gerenciado pela YG Entertainment?',
    options: ['TWICE', 'MAMAMOO', 'BLACKPINK', '2NE1'],
    correct: 2,
    explanation: '"Lovesick Girls" (2020) é um single do BLACKPINK. A YG Entertainment gerencia o grupo desde 2016.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do light stick do BTS?',
    options: ['ARMY Bomb', 'Purple Stick', 'BTS Wand', 'Bulletproof Light'],
    correct: 0,
    explanation: 'O light stick oficial do BTS é chamado de ARMY Bomb, e tem o design de uma bomba dourada com luz roxa/colorida.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo masculino é famoso pelo conceito de "pirata" e lançou "Fireworks (I\'ll Be There)"?',
    options: ['MONSTA X', 'ATEEZ', 'Stray Kids', 'ASTRO'],
    correct: 1,
    explanation: 'ATEEZ é famoso por seu conceito de pirata/aventureiro e lançou "Fireworks (I\'ll Be There)" em 2021.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de K-Pop se chama "Bangtan Sonyeondan" em coreano?',
    options: ['EXO', 'BIGBANG', 'BTS', 'GOT7'],
    correct: 2,
    explanation: 'BTS é a abreviação de "Bangtan Sonyeondan" (방탄소년단), que significa "Garotos à Prova de Balas" em coreano.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual membro do BTS foi o primeiro a completar o serviço militar obrigatório do grupo?',
    options: ['RM', 'Jin', 'Suga', 'J-Hope'],
    correct: 1,
    explanation: 'Jin foi o primeiro membro do BTS a entrar para o serviço militar, em dezembro de 2022, sendo dispensado em junho de 2024.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de meninas da 4ª geração é composto por NewJeans?',
    options: ['ADOR', 'HYBE Labels', 'SM Entertainment', 'JYP Entertainment'],
    correct: 0,
    explanation: 'NewJeans é gerenciado pela ADOR (All Doors Open Records), uma subsidiária da HYBE, fundada por Min Hee-jin.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Qual foi o grupo de K-Pop pioneiro a realizar uma turnê mundial esgotando estádios em todos os continentes?',
    options: ['EXO', 'BIGBANG', 'BTS', 'Super Junior'],
    correct: 2,
    explanation: 'O BTS foi o primeiro grupo de K-Pop a realizar turnês mundiais esgotando estádios em todos os continentes, incluindo a Love Yourself World Tour (2018-2019).',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome do reality show de sobrevivência que criou o grupo Kep1er?',
    options: ['Produce 101', 'Girls Planet 999', 'I-Land', 'My Teenage Girl'],
    correct: 1,
    explanation: 'Kep1er foi formado em 2022 através do reality show "Girls Planet 999" da Mnet, com integrantes da Coreia, China e Japão.',
    category: 'k-pop', difficulty: 'hard',
  },

  // ─── K-Drama ──────────────────────────────────────────────────────────────
  {
    question: 'Qual K-Drama foi o primeiro a ganhar o Emmy Internacional de Melhor Série de Drama?',
    options: ['My Mister', 'Squid Game', 'Extraordinary Attorney Woo', 'Crash Landing on You'],
    correct: 1,
    explanation: '"Round 6" (Squid Game) ganhou o Emmy Internacional de Melhor Série de Drama em 2022, tornando-se a primeira produção coreana a conquistar esse prêmio.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual ator interpretou o protagonista Gi-hun em "Round 6" (Squid Game)?',
    options: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'O Yeong-su'],
    correct: 0,
    explanation: 'Lee Jung-jae interpretou Seong Gi-hun, o número 456, protagonista de "Round 6". Ele também ganhou o Emmy de Melhor Ator pela atuação.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Em qual plataforma de streaming "Round 6" (Squid Game) foi lançado em 2021?',
    options: ['Amazon Prime', 'Disney+', 'Netflix', 'HBO Max'],
    correct: 2,
    explanation: '"Round 6" foi lançado na Netflix em setembro de 2021 e se tornou a série mais assistida da plataforma em menos de um mês.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual K-Drama estrelado por Son Ye-jin e Hyun Bin os levou a se casar na vida real?',
    options: ['Secret Garden', 'My Love from the Star', 'Crash Landing on You', 'The World of the Married'],
    correct: 2,
    explanation: '"Crash Landing on You" (2019-2020) uniu Son Ye-jin e Hyun Bin, que se casaram em março de 2022 e tiveram um filho.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual K-Drama de 2019 narra a história de uma jovem coreana que acidentalmente pousa na Coreia do Norte?',
    options: ['Kingdom', 'Vagabond', 'Crash Landing on You', 'Arthdal Chronicles'],
    correct: 2,
    explanation: '"Crash Landing on You" (tvN, 2019) conta a história de Yoon Se-ri que cai acidentalmente na Coreia do Norte e se apaixona por um oficial do exército.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual K-Drama histórico ambientado na era Joseon combina política e zumbis?',
    options: ['Mr. Sunshine', 'Rookie Historian', 'Kingdom', 'The Red Sleeve'],
    correct: 2,
    explanation: '"Kingdom" (Netflix, 2019) é um thriller histórico ambientado na era Joseon que mistura política do reino com uma epidemia de zumbis.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual ator de K-Drama interpretou o personagem Lee Gon em "The King: Eternal Monarch"?',
    options: ['Ji Chang-wook', 'Lee Min-ho', 'Kim Soo-hyun', 'Park Seo-joon'],
    correct: 1,
    explanation: 'Lee Min-ho interpretou o Rei Lee Gon em "The King: Eternal Monarch" (2020), um drama de fantasia sobre dois mundos paralelos.',
    category: 'k-drama', difficulty: 'medium',
  },
  {
    question: 'Qual drama coreano popularizou o termo "Hallyu" (Onda Coreana) no final dos anos 90?',
    options: ['Full House', 'What Is Love', 'Winter Sonata', 'My Sassy Girl'],
    correct: 1,
    explanation: '"What Is Love" (1991) e especialmente "星あなた" ("You Are My Destiny") foram os primeiros a despertar interesse, mas o Hallyu foi batizado após dramas como "What is Love" e "Jealousy" explodirem na China.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual K-Drama de 2014 com Kim Soo-hyun como alienígena se tornou um fenômeno na Ásia?',
    options: ['Healer', 'My Love from the Star', 'The Inheritors', 'Pinocchio'],
    correct: 1,
    explanation: '"My Love from the Star" (2013-2014) com Kim Soo-hyun como um alienígena que chegou à Terra 400 anos atrás foi um megassucesso em toda a Ásia.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual atriz interpretou a advogada com autismo em "Extraordinary Attorney Woo"?',
    options: ['Kim Go-eun', 'Park Eun-bin', 'Kim Tae-ri', 'Lee Se-young'],
    correct: 1,
    explanation: 'Park Eun-bin interpretou Woo Young-woo em "Extraordinary Attorney Woo" (2022), papel que lhe rendeu vários prêmios e reconhecimento internacional.',
    category: 'k-drama', difficulty: 'medium',
  },
  {
    question: 'Qual K-Drama de 2021 sobre um escritor frustrado que vive dentro de seus romances foi premiado internacionalmente?',
    options: ['Snowdrop', 'Navillera', 'Hometown Cha-Cha-Cha', 'The Devil Judge'],
    correct: 1,
    explanation: '"Navillera" (2021) conta a história de um homem de 70 anos que realiza o sonho de aprender balé. É um drama sobre sonhos e segunda chance, muito elogiado.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual canal de televisão coreano é conhecido por K-Dramas de alta qualidade como "Goblin" e "Reply 1988"?',
    options: ['KBS', 'MBC', 'SBS', 'tvN'],
    correct: 3,
    explanation: 'A tvN (Total Variety Network), um canal a cabo, é conhecida por produções de alto nível como "Goblin", "Reply 1988" e "Crash Landing on You".',
    category: 'k-drama', difficulty: 'medium',
  },
  {
    question: 'Qual K-Drama de 2016 com Park Bo-gum como jovem monarca cativou a Ásia?',
    options: ['Love in the Moonlight', 'Moonlight Drawn by Clouds', 'The Moon That Embraces the Sun', 'Ruler: Master of the Mask'],
    correct: 1,
    explanation: '"Moonlight Drawn by Clouds" (KBS, 2016), também chamado "Love in the Moonlight", tem Park Bo-gum como o príncipe Crown e foi um grande sucesso.',
    category: 'k-drama', difficulty: 'medium',
  },
  {
    question: 'Qual dupla de atores de K-Drama ficou famosa como "OTP" (One True Pairing) no drama "Descendants of the Sun"?',
    options: ['Lee Jong-suk e Park Shin-hye', 'Song Joong-ki e Song Hye-kyo', 'Ji Chang-wook e Kim Ji-won', 'Lee Min-ho e Jun Ji-hyun'],
    correct: 1,
    explanation: 'Song Joong-ki e Song Hye-kyo se tornaram o casal mais famoso do K-Drama em 2016 com "Descendants of the Sun", e chegaram a se casar na vida real (divorciando-se em 2019).',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual atriz coreana venceu o Oscar de Melhor Atriz Coadjuvante em 2025?',
    options: ['Jun Ji-hyun', 'Song Hye-kyo', 'Kim Tae-ri', 'Zoe Saldana'],
    correct: 3,
    explanation: 'Zoe Saldana é americana. A atriz coreana Youn Yuh-jung ganhou o Oscar de Melhor Atriz Coadjuvante em 2021 por "Minari" — foi a primeira atriz coreana a ganhar o prêmio.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual drama histórico de 2021 narra a história do príncipe Sejong, criador do alfabeto hangul?',
    options: ['Mr. Queen', 'The Red Sleeve', 'River Where the Moon Rises', 'The King\'s Affection'],
    correct: 3,
    explanation: '"The King\'s Affection" aborda temas da era Joseon, mas foi "The Great King Sejong" quem tratou diretamente da criação do hangul.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual é o termo coreano para o gênero de drama que mistura romance com elementos sobrenaturais?',
    options: ['Melo', 'Fusion', 'Fantasy romance', 'Sageuk'],
    correct: 3,
    explanation: '"Sageuk" é o termo para dramas históricos coreanos, enquanto dramas com elementos sobrenaturais são geralmente chamados de "fantasy" ou "fusion sageuk" quando combinam história com fantasia.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual ator de "Goblin" interpretou o personagem imortal Kim Shin?',
    options: ['Lee Dong-wook', 'Gong Yoo', 'Park Seo-joon', 'Wi Ha-joon'],
    correct: 1,
    explanation: 'Gong Yoo interpretou Kim Shin, o Goblin imortal, em "Goblin: The Lonely and Great God" (tvN, 2016-2017).',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual plataforma de streaming sul-coreana compete com a Netflix no mercado doméstico?',
    options: ['Wavve', 'Viki', 'Kocowa', 'Laftel'],
    correct: 0,
    explanation: 'Wavve é a principal plataforma de streaming sul-coreana, formada pela fusão de serviços das emissoras públicas KBS, MBC e SBS com a SK Telecom.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Em que ano foi ao ar o drama "Winter Sonata", que contribuiu para a primeira onda Hallyu na Ásia?',
    options: ['1999', '2001', '2002', '2005'],
    correct: 2,
    explanation: '"Winter Sonata" foi ao ar na KBS2 em 2002 e gerou um fenômeno na Ásia, especialmente no Japão, onde o protagonista Bae Yong-jun se tornou um ídolo.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual personagem de "Round 6" ficou famoso pela roupa rosa de segurança e máscara preta?',
    options: ['Os jogadores', 'Os guardas (soldados)', 'O Front Man', 'O VIP'],
    correct: 1,
    explanation: 'Os guardas de "Round 6" usam uniformes rosas com máscaras pretas em formas geométricas (triângulo, quadrado, círculo), tornando-se um ícone visual.',
    category: 'k-drama', difficulty: 'easy',
  },

  // ─── Cultura ──────────────────────────────────────────────────────────────
  {
    question: 'O que é "Hallyu"?',
    options: ['Um prato típico coreano', 'A Onda Coreana de cultura popular', 'Um festival tradicional', 'Um estilo de arquitetura'],
    correct: 1,
    explanation: '"Hallyu" (한류) significa "Onda Coreana" e se refere à disseminação global da cultura popular coreana: K-Pop, K-Drama, cinema, comida, beleza e moda.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual prato coreano fermentado é considerado patrimônio cultural imaterial pela UNESCO?',
    options: ['Bibimbap', 'Tteokbokki', 'Kimchi', 'Japchae'],
    correct: 2,
    explanation: 'O Kimchi, prato fermentado de repolho apimentado, foi reconhecido pela UNESCO como patrimônio cultural imaterial da humanidade em 2013.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do tradicional vestuário coreano usado em cerimônias e festivais?',
    options: ['Kimono', 'Hanbok', 'Cheongsam', 'Ao dai'],
    correct: 1,
    explanation: 'O Hanbok (한복) é o traje tradicional coreano, com cores vibrantes e silhuetas elegantes, usado em ocasiões especiais como casamentos e o Ano Novo Lunar.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do festival coreano que celebra o Ano Novo Lunar?',
    options: ['Chuseok', 'Seollal', 'Dano', 'Jeongwol Daeboreum'],
    correct: 1,
    explanation: 'Seollal (설날) é o Ano Novo Lunar coreano, um dos feriados mais importantes do país, quando as famílias se reúnem para reverenciar ancestrais e compartilhar refeições.',
    category: 'cultura', difficulty: 'medium',
  },
  {
    question: 'O que é "Chuseok"?',
    options: ['Uma arte marcial coreana', 'O festival da colheita de outono coreano', 'Um tipo de sopa tradicional', 'A cerimônia do chá coreana'],
    correct: 1,
    explanation: 'Chuseok (추석) é o maior festival coreano, celebrado no 15º dia do 8º mês lunar, equivalente ao Dia de Ação de Graças — as famílias se reúnem para celebrar a colheita.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o significado do gesto de fazer um "coração com os dedos" popular na cultura coreana?',
    options: ['Amizade', 'Gratidão', 'Amor ou afeição', 'Boa sorte'],
    correct: 2,
    explanation: 'O "finger heart" (dedos em forma de coração) é um gesto popular na Coreia que representa amor ou afeição, amplamente usado por ídolos de K-Pop.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o prato coreano composto por arroz coberto com vegetais, carne e ovo, misturado com pasta de pimenta?',
    options: ['Samgyeopsal', 'Kimchi jjigae', 'Bibimbap', 'Doenjang jjigae'],
    correct: 2,
    explanation: 'Bibimbap (비빔밥) significa literalmente "arroz misturado" — é servido com vegetais variados, carne, ovo frito e gochujang (pasta de pimenta vermelha).',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'O que é "K-Beauty"?',
    options: ['Uma marca de cosméticos coreana', 'A indústria e tendências de beleza da Coreia do Sul', 'Um programa de TV sobre beleza', 'Um tipo de maquiagem teatral'],
    correct: 1,
    explanation: 'K-Beauty se refere à indústria de beleza coreana e suas tendências, conhecida por inovações em skincare como a rotina de 10 passos, BB cream, e produtos com ingredientes inusitados.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome da arte marcial coreana que se tornou esporte olímpico?',
    options: ['Hapkido', 'Ssireum', 'Taekwondo', 'Tang Soo Do'],
    correct: 2,
    explanation: 'O Taekwondo é a arte marcial coreana que se tornou esporte olímpico oficial nos Jogos de Sydney 2000. É famoso pelos chutes acrobáticos.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'O que é "Manhwa"?',
    options: ['Quadrinhos coreanos', 'Animação japonesa', 'Um instrumento musical coreano', 'Um tipo de dança tradicional'],
    correct: 0,
    explanation: 'Manhwa (만화) são os quadrinhos e histórias em quadrinhos originários da Coreia do Sul, lidos geralmente de cima para baixo (scroll vertical), ao contrário dos mangás japoneses.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do ritual coreano de reverência aos ancestrais durante Chuseok e Seollal?',
    options: ['Jesa', 'Jeon', 'Charye', 'Sebae'],
    correct: 2,
    explanation: 'Charye (차례) é o ritual de oferenda aos ancestrais realizado durante Seollal e Chuseok, onde a família prepara comidas especiais e faz prostrações.',
    category: 'cultura', difficulty: 'hard',
  },
  {
    question: 'Qual é o nome do instrumento de percussão coreano feito de bronze, semelhante a um gongo?',
    options: ['Haegeum', 'Kkwaenggwari', 'Daegeum', 'Gayageum'],
    correct: 1,
    explanation: 'O Kkwaenggwari (꽹과리) é um pequeno gongo de bronze usado em música folclórica coreana, especialmente no nongak (música agrícola).',
    category: 'cultura', difficulty: 'hard',
  },
  {
    question: 'Qual filme coreano ganhou a Palma de Ouro no Festival de Cannes em 2019?',
    options: ['Okja', 'The Handmaiden', 'Parasite', 'Burning'],
    correct: 2,
    explanation: '"Parasite" (기생충) do diretor Bong Joon-ho ganhou a Palma de Ouro em Cannes 2019 e depois o Oscar de Melhor Filme em 2020.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual diretor coreano realizou o filme "Parasite"?',
    options: ['Park Chan-wook', 'Lee Chang-dong', 'Kim Ki-duk', 'Bong Joon-ho'],
    correct: 3,
    explanation: 'Bong Joon-ho dirigiu "Parasite" (2019), tornando-se o primeiro diretor coreano e asiático a ganhar a Palma de Ouro em Cannes e o Oscar de Melhor Diretor.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do tipo de sauna seco tradicional coreano, frequentemente encontrado em spas (jjimjilbang)?',
    options: ['Hanjeungmak', 'Ondol', 'Fogueira de sal', 'Bulgogi'],
    correct: 0,
    explanation: 'Hanjeungmak (한증막) é a sauna a vapor ou seco tradicional coreana, encontrada nos jjimjilbang (centros de saúde). O ondol é o sistema de aquecimento pelo piso.',
    category: 'cultura', difficulty: 'hard',
  },
  {
    question: 'Qual é o nome do sistema de escrita coreano, criado no século XV?',
    options: ['Hanja', 'Hangul', 'Katakana', 'Bopomofo'],
    correct: 1,
    explanation: 'O Hangul (한글) foi criado pelo Rei Sejong o Grande e seus estudiosos em 1443, durante a Dinastia Joseon, para aumentar a alfabetização do povo coreano.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'O que é "Aegyo" no contexto da cultura coreana?',
    options: ['Um tipo de saudação formal', 'Comportamento fofo e infantil para parecer adorável', 'Uma técnica vocal', 'Um estilo de maquiagem'],
    correct: 1,
    explanation: 'Aegyo (애교) é o comportamento propositalmente fofo e infantil — como voz aguda, expressões faciais exageradas e gestos bonitos — muito comum entre ídolos de K-Pop.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do bairro de Seoul famoso por suas tendências de moda e vida noturna?',
    options: ['Insadong', 'Bukchon', 'Hongdae', 'Myeongdong'],
    correct: 2,
    explanation: 'Hongdae (홍대) é o bairro próximo à Universidade Hongik, famoso por sua cena artística, música ao vivo, moda alternativa e vida noturna.',
    category: 'cultura', difficulty: 'medium',
  },
  {
    question: 'O que é "Webtoon"?',
    options: ['Animação 3D coreana', 'Quadrinho digital publicado online, vertical e em cores', 'Um desenho animado infantil', 'Um filme de animação'],
    correct: 1,
    explanation: 'Webtoon é o formato de quadrinhos digitais desenvolvido na Coreia do Sul, publicado verticalmente para leitura em smartphones, com muitos adaptados para K-Dramas e filmes.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do maior festival de K-Pop realizado anualmente em Seoul?',
    options: ['KCON', 'MAMA Awards', 'Mnet Asian Music Awards', 'Korean Music Festival'],
    correct: 1,
    explanation: 'O MAMA (Mnet Asian Music Awards) é um dos maiores e mais prestigiados prêmios musicais da Ásia, realizado anualmente com cerimônias grandiosas.',
    category: 'cultura', difficulty: 'medium',
  },

  // ─── História ─────────────────────────────────────────────────────────────
  {
    question: 'Qual dinastia governou a Coreia por mais de 500 anos, até 1897?',
    options: ['Goryeo', 'Silla', 'Joseon', 'Baekje'],
    correct: 2,
    explanation: 'A Dinastia Joseon (조선) governou a Coreia de 1392 a 1897, sendo um dos períodos mais longos de um único governo na história mundial.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual rei coreano é considerado um dos maiores monarcas da história por criar o Hangul?',
    options: ['Gwanggaeto', 'Taejo', 'Sejong', 'Seonjo'],
    correct: 2,
    explanation: 'O Rei Sejong o Grande (세종대왕, r. 1418-1450) é considerado o maior monarca coreano, responsável pela criação do Hangul e por enormes avanços científicos e culturais.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Em que ano a Coreia foi dividida em Norte e Sul?',
    options: ['1943', '1945', '1950', '1953'],
    correct: 1,
    explanation: 'A divisão da Coreia ocorreu em 1945, após o fim da Segunda Guerra Mundial, ao longo do paralelo 38°N. O Norte ficou sob influência soviética e o Sul, americana.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Quando começou a Guerra da Coreia?',
    options: ['1945', '1948', '1950', '1953'],
    correct: 2,
    explanation: 'A Guerra da Coreia começou em 25 de junho de 1950, quando a Coreia do Norte invadiu a Coreia do Sul. O conflito durou até o armistício de julho de 1953.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual potência colonizou a Coreia de 1910 até 1945?',
    options: ['China', 'Rússia', 'Estados Unidos', 'Japão'],
    correct: 3,
    explanation: 'O Japão colonizou a Coreia de 1910 a 1945, período de grande supressão cultural e exploração econômica, que terminou com a derrota japonesa na Segunda Guerra Mundial.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'O que foi o "Milagre do Rio Han"?',
    options: ['Uma batalha histórica', 'A rápida industrialização e crescimento econômico da Coreia do Sul', 'A construção de uma represa', 'Um evento esportivo'],
    correct: 1,
    explanation: 'O "Milagre do Rio Han" (한강의 기적) refere-se ao extraordinário crescimento econômico da Coreia do Sul após a Guerra da Coreia, passando de um dos países mais pobres a uma das maiores economias em apenas décadas.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome do movimento de independência coreana contra a ocupação japonesa, iniciado em 1º de março de 1919?',
    options: ['Movimento de 1º de Março', 'Revolução de Abril', 'Revolta de Donghak', 'Movimento Gwangju'],
    correct: 0,
    explanation: 'O Movimento de 1º de Março (삼일운동, Sam-il Undong) de 1919 foi uma das primeiras manifestações públicas de resistência à ocupação japonesa, com milhares de coreanos saindo às ruas pedindo independência.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual foi o primeiro presidente da República da Coreia (Coreia do Sul)?',
    options: ['Park Chung-hee', 'Roh Moo-hyun', 'Syngman Rhee', 'Chun Doo-hwan'],
    correct: 2,
    explanation: 'Syngman Rhee (이승만) foi o primeiro presidente da República da Coreia, servindo de 1948 a 1960, quando renunciou após os protestos da Revolução de Abril.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Em que cidade foi realizado os Jogos Olímpicos de Verão de 1988?',
    options: ['Busan', 'Incheon', 'Seoul', 'Daegu'],
    correct: 2,
    explanation: 'Seoul sediou os Jogos Olímpicos de Verão de 1988, um marco para a Coreia do Sul — foi o primeiro evento global a mostrar a modernização do país para o mundo.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do período de três reinos que precedeu a unificação coreana?',
    options: ['Goryeo, Joseon e Silla', 'Goguryeo, Baekje e Silla', 'Gojoseon, Goryeo e Joseon', 'Silla, Gaya e Baekje'],
    correct: 1,
    explanation: 'O período dos Três Reinos (삼국 시대) é composto por Goguryeo (norte), Baekje (sudoeste) e Silla (sudeste), que existiram entre aproximadamente 57 a.C. e 668 d.C.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome do estado coreano fundado lendariamente por Dangun há mais de 4.000 anos?',
    options: ['Goryeo', 'Joseon', 'Gojoseon', 'Buyeo'],
    correct: 2,
    explanation: 'Gojoseon (고조선, "Joseon Antigo") é o primeiro estado coreano, lendariamente fundado por Dangun em 2333 a.C., e é a raiz da identidade nacional coreana.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual general almirante coreano é lendário por derrotar a invasão naval japonesa no século XVI usando "barcos-tartaruga"?',
    options: ['Kim Yusin', 'Yi Sun-sin', 'Gang Gamchan', 'Eulji Mundeok'],
    correct: 1,
    explanation: 'O Almirante Yi Sun-sin (이순신) é o herói militar mais reverenciado da Coreia, famoso por usar os geobukseon (barcos-tartaruga) para defender o país durante as invasões japonesas de 1592-1598.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Em que ano Seoul sediou a Copa do Mundo FIFA, com a Coreia do Sul chegando às semifinais?',
    options: ['1998', '2000', '2002', '2006'],
    correct: 2,
    explanation: 'A Copa do Mundo de 2002 foi co-sediada por Coreia do Sul e Japão. A Coreia do Sul surpreendeu o mundo chegando às semifinais — o melhor resultado de uma seleção asiática.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual é o nome do período de democratização da Coreia do Sul na segunda metade do século XX, após décadas de ditadura militar?',
    options: ['Revolução de Junho', 'Movimento Pro-Democracia de Junho', 'Primavera de Seoul', 'Reforma Democrática'],
    correct: 1,
    explanation: 'O Movimento Democrático de Junho de 1987 (6월 민주 항쟁) foi a série de protestos populares que forçou o governo militar a aceitar eleições diretas, iniciando a democratização do país.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual imperatriz coreana foi assassinada por agentes japoneses em 1895?',
    options: ['Rainha Inhyeon', 'Imperatriz Myeongseong', 'Rainha Jeongsun', 'Imperatriz Sunmyeong'],
    correct: 1,
    explanation: 'A Imperatriz Myeongseong (명성황후), também chamada de "Rainha Min", foi assassinada por agentes japoneses no Palácio Gyeongbok em outubro de 1895, em um evento que chocou o mundo.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual foi o nome da Coreia durante a Idade Média, que deu origem ao nome "Korea" em idiomas ocidentais?',
    options: ['Joseon', 'Goryeo', 'Silla', 'Gojoseon'],
    correct: 1,
    explanation: 'A dinastia Goryeo (고려, 918-1392) deu origem ao nome "Korea" — os mercadores árabes e persas comerciavam com esse reino e levaram o nome para o ocidente.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual tecnologia de impressão foi desenvolvida na Coreia antes de Gutenberg, durante o período Goryeo?',
    options: ['Xilografia', 'Litografia', 'Tipos móveis metálicos', 'Serigrafia'],
    correct: 2,
    explanation: 'A Coreia desenvolveu tipos móveis metálicos por volta de 1230 d.C., mais de 200 anos antes de Gutenberg na Europa. O "Jikji" (1377) é o livro mais antigo impresso com tipos móveis metálicos.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual é o nome do movimento estudantil de 1980 que resultou em um massacre brutal durante a ditadura militar na Coreia do Sul?',
    options: ['Revolução de Abril', 'Levante de Gwangju', 'Movimento de 1º de Março', 'Rebelião de Daegu'],
    correct: 1,
    explanation: 'O Levante de Gwangju (광주 민주화 운동) de maio de 1980 foi um movimento pro-democracia brutalmente suprimido pelo general Chun Doo-hwan, resultando em centenas de mortes.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual foi o grande incêndio natural que devastou a Coreia no século XIII, destruindo o Grande Cânone Budista?',
    options: ['A invasão mongol', 'A invasão japonesa', 'Uma erupção vulcânica', 'Um terremoto'],
    correct: 0,
    explanation: 'As invasões mongóis do século XIII destruíram o original Tripitaka Koreana. Os coreanos refizeram a obra em madeira (팔만대장경), com mais de 80.000 tábuas, conservadas até hoje em Haeinsa.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual é o nome da Zona Desmilitarizada (DMZ) que separa as duas Coreias?',
    options: ['Linha de armistício', 'Paralelo 38', 'Zona Tampão Coreana', 'Fronteira Kim-Mac'],
    correct: 1,
    explanation: 'A divisão das Coreias segue aproximadamente o Paralelo 38 (38º latitude norte). A DMZ criada pelo Armistício de 1953 tem 4km de largura ao longo dessa linha.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual capital histórica é famosa pelo Palácio Gyeongbokgung e foi construída no início da Dinastia Joseon?',
    options: ['Gyeongju', 'Gaeseong', 'Hanyang', 'Pyongyang'],
    correct: 2,
    explanation: 'Hanyang (한양) foi a capital fundada pela Dinastia Joseon em 1394. Ela se tornou a Seoul moderna. Gyeongbokgung foi o principal palácio real construído ali.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual religião foi a oficial durante a Dinastia Goryeo e ainda é importante na Coreia hoje?',
    options: ['Confucionismo', 'Xamanismo', 'Budismo', 'Catolicismo'],
    correct: 2,
    explanation: 'O Budismo foi a religião oficial durante a Dinastia Goryeo (918-1392). Monumentos budistas como o Haeinsa e o Bulguksa testemunham essa influência.',
    category: 'história', difficulty: 'medium',
  },
]

async function main() {
  console.log(`Inserindo ${questions.length} novas perguntas…`)

  let inserted = 0
  for (const q of questions) {
    await prisma.quizQuestion.create({
      data: {
        question:     q.question,
        options:      q.options,
        correct:      q.correct,
        explanation:  q.explanation,
        category:     q.category,
        difficulty:   q.difficulty,
        relatedHref:  q.relatedHref  ?? null,
        relatedLabel: q.relatedLabel ?? null,
        isActive: true,
      },
    })
    inserted++
    process.stdout.write(`\r${inserted}/${questions.length}`)
  }

  console.log(`\nConcluído. Total inserido: ${inserted}`)
  const total = await prisma.quizQuestion.count({ where: { isActive: true } })
  console.log(`Total ativo no banco: ${total}`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
