/**
 * Seed QuizQuestion table with initial questions.
 * Run: DATABASE_URL=... npx tsx scripts/seed-quiz-questions.ts
 */
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://hallyuhub:hallyuhub@127.0.0.1:5433/hallyuhub_production',
})
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) as any })

const questions = [
  // ─── K-Pop ────────────────────────────────────────────────────────────────
  {
    question: 'Qual grupo de K-Pop detém o recorde de mais álbuns vendidos na história da Coreia do Sul?',
    options: ['EXO', 'BIGBANG', 'BTS', 'BLACKPINK'],
    correct: 2,
    explanation: 'O BTS é o grupo com mais álbuns vendidos na história da Coreia do Sul, com dezenas de milhões de cópias ao redor do mundo.',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/sm-hybe-yg-jyp-como-as-grandes-agencias-kpop-funcionam',
    relatedLabel: 'Como funcionam as big four do K-Pop',
  },
  {
    question: 'Qual é o nome do fandom oficial do BTS?',
    options: ['Blink', 'ARMY', 'EXO-L', 'Once'],
    correct: 1,
    explanation: 'O fandom do BTS se chama ARMY (Adorable Representative MC for Youth).',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/fandoms-kpop-light-sticks-fan-chants-fansigns',
    relatedLabel: 'Fandoms de K-Pop: light sticks e fan chants',
  },
  {
    question: 'Qual sistema de entretenimento formou grupos como EXO, NCT e aespa?',
    options: ['HYBE', 'JYP Entertainment', 'YG Entertainment', 'SM Entertainment'],
    correct: 3,
    explanation: 'A SM Entertainment, fundada em 1995, formou grupos icônicos como EXO, NCT e aespa.',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/sm-hybe-yg-jyp-como-as-grandes-agencias-kpop-funcionam',
    relatedLabel: 'SM, HYBE, YG e JYP: como funcionam',
  },
  {
    question: 'Quantos membros tem o grupo TWICE?',
    options: ['7', '8', '9', '12'],
    correct: 2,
    explanation: 'O TWICE é composto por 9 membros, formado em 2015 pela JYP Entertainment através do reality show Sixteen.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo lançou o álbum "Map of the Soul: Persona"?',
    options: ['EXO', 'BTS', 'SEVENTEEN', 'GOT7'],
    correct: 1,
    explanation: '"Map of the Soul: Persona" foi lançado pelo BTS em abril de 2019 e bateu recordes de pré-venda.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo feminino ficou famoso pelo hit "Ddu-Du Ddu-Du"?',
    options: ['TWICE', 'Red Velvet', 'BLACKPINK', 'aespa'],
    correct: 2,
    explanation: '"Ddu-Du Ddu-Du" do BLACKPINK (2018) é um dos MVs de K-Pop feminino mais vistos de todos os tempos.',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/jennie-blackpink-rainha-k-pop-conquistou-mundo',
    relatedLabel: 'Jennie: a rainha do K-Pop',
  },
  {
    question: 'Qual empresa gerencia o grupo BTS?',
    options: ['SM Entertainment', 'YG Entertainment', 'JYP Entertainment', 'HYBE'],
    correct: 3,
    explanation: 'O BTS é gerenciado pela HYBE (anteriormente Big Hit Entertainment), fundada por Bang Si-hyuk.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo feminino tem como fandom o nome "BLINK"?',
    options: ['TWICE', 'BLACKPINK', 'Red Velvet', 'aespa'],
    correct: 1,
    explanation: 'O fandom oficial do BLACKPINK se chama BLINK, combinando "black" e "pink".',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual artista é conhecida como "Rainha do K-Pop Solo" e também atua em dramas?',
    options: ['Suzy', 'IU', 'Taeyeon', 'Jisoo'],
    correct: 1,
    explanation: 'IU é considerada a artista mais completa da Coreia, com sucessos como "LILAC" e dramas como "My Mister".',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/iu-artista-mais-completa-da-coreia',
    relatedLabel: 'IU: cantora, atriz e compositora',
  },
  {
    question: 'Quantos membros compõem o grupo SEVENTEEN?',
    options: ['12', '13', '17', '9'],
    correct: 1,
    explanation: 'O SEVENTEEN tem 13 membros divididos em três unidades. O nome "17" vem de 13 + 3 unidades + 1 equipe.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo lançou o hit "Ko Ko Bop" em 2017?',
    options: ['BTS', 'GOT7', 'EXO', 'MONSTA X'],
    correct: 2,
    explanation: 'O EXO lançou "Ko Ko Bop" como parte do álbum "The War" (2017), um dos álbuns mais vendidos daquele ano.',
    category: 'k-pop', difficulty: 'medium',
    relatedHref: '/blog/exo-a-geracao-que-vendeu-30-milhoes-de-albuns',
    relatedLabel: 'EXO: a geração que vendeu 30 milhões de álbuns',
  },
  {
    question: 'Qual grupo feminino lançou o hit "Gee" em 2009?',
    options: ['2NE1', 'KARA', "Girls' Generation (SNSD)", 'Wonder Girls'],
    correct: 2,
    explanation: '"Gee" do Girls\' Generation ficou 9 semanas no topo das paradas sul-coreanas em 2009.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de 4ª geração debutou com o conceito "Fearless" em 2022?',
    options: ['aespa', 'ITZY', 'LE SSERAFIM', 'NewJeans'],
    correct: 2,
    explanation: 'LE SSERAFIM debutou em 2022 com "FEARLESS". O nome é um anagrama de "I\'M FEARLESS".',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de K-Pop foi formado pelo reality show "Produce 101" em 2016?',
    options: ['IOI', 'WANNA ONE', 'IZ*ONE', 'X1'],
    correct: 0,
    explanation: 'IOI foi o primeiro grupo formado pelo Produce 101 (2016). Era feminino e temporário.',
    category: 'k-pop', difficulty: 'medium',
    relatedHref: '/blog/produce-101-reality-show-kpop-historia-escandalo',
    relatedLabel: 'Produce 101: o reality que reformatou o K-Pop',
  },
  {
    question: 'Em que país nasceu a integrante do BLACKPINK Lisa?',
    options: ['Coreia do Sul', 'Japão', 'Tailândia', 'China'],
    correct: 2,
    explanation: 'Lisa (Lalisa Manobal) nasceu na Tailândia em 1997. É a membro mais seguida individualmente nas redes sociais.',
    category: 'k-pop', difficulty: 'easy',
    relatedHref: '/blog/lisa-blackpink-trajetoria-carreira-solo',
    relatedLabel: 'Lisa: de Bangkok para o mundo',
  },
  {
    question: 'Qual integrante do BTS é o líder e principal compositor do grupo?',
    options: ['Jin', 'Jungkook', 'RM', 'V'],
    correct: 2,
    explanation: 'RM (Kim Namjoon) é o líder e principal compositor. Também falou em nome do grupo na ONU.',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Qual grupo é formado pelas subunidades NCT 127, NCT Dream e WayV?',
    options: ['EXO', 'SUPER JUNIOR', 'NCT', 'BIGBANG'],
    correct: 2,
    explanation: 'O NCT (Neo Culture Technology) é um grupo sem limite de membros da SM Entertainment, dividido em várias subunidades.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de K-Pop tem como fandom o nome "ONCE"?',
    options: ['TWICE', 'SHINee', 'MONSTA X', 'GOT7'],
    correct: 0,
    explanation: 'O fandom do TWICE se chama ONCE porque "se você amar o TWICE, elas amarão você de volta duas vezes".',
    category: 'k-pop', difficulty: 'easy',
  },
  {
    question: 'Stray Kids são gerenciados por qual empresa?',
    options: ['SM Entertainment', 'JYP Entertainment', 'HYBE', 'YG Entertainment'],
    correct: 1,
    explanation: 'Stray Kids foram formados pela JYP Entertainment em 2017 através do reality show de mesmo nome.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo feminino foi o primeiro a atingir 1 bilhão de streams no Spotify com um álbum?',
    options: ['BLACKPINK', "Girls' Generation", 'TWICE', 'aespa'],
    correct: 0,
    explanation: 'BLACKPINK foi o primeiro grupo feminino de K-Pop a atingir 1 bilhão de streams no Spotify.',
    category: 'k-pop', difficulty: 'hard',
  },
  {
    question: 'Qual é o nome completo em inglês da agência do BTS antes de mudar para HYBE?',
    options: ['Big Bang Entertainment', 'Big Hit Entertainment', 'BigHouse Music', 'BigTime Records'],
    correct: 1,
    explanation: 'A empresa era chamada Big Hit Entertainment antes de mudar para HYBE Corporation em 2021.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Qual grupo de K-Pop foi o primeiro a se apresentar no Coachella?',
    options: ['BTS', 'BLACKPINK', '2NE1', 'EXO'],
    correct: 1,
    explanation: 'BLACKPINK foi o primeiro grupo de K-Pop e o primeiro artista asiático a se apresentar no Coachella, em 2019.',
    category: 'k-pop', difficulty: 'medium',
  },
  {
    question: 'Em qual premiação o BTS ganhou seu primeiro Daesang?',
    options: ['MAMA 2016', 'Melon Music Awards 2016', 'Golden Disc Awards 2017', 'Gaon Chart Awards 2017'],
    correct: 1,
    explanation: 'O BTS ganhou seu primeiro Daesang (Album of the Year) no Melon Music Awards 2016.',
    category: 'k-pop', difficulty: 'hard',
  },

  // ─── K-Drama ──────────────────────────────────────────────────────────────
  {
    question: 'Qual K-Drama foi o primeiro da Netflix a alcançar o 1º lugar em mais de 90 países simultaneamente?',
    options: ['Crash Landing on You', 'Vincenzo', 'Squid Game', 'My Love from the Star'],
    correct: 2,
    explanation: '"Squid Game" estreou em setembro de 2021 e rapidamente se tornou a série mais assistida da Netflix na história.',
    category: 'k-drama', difficulty: 'easy',
    relatedHref: '/blog/squid-game-analise-cultural-netflix-hallyu',
    relatedLabel: 'Squid Game e o que mudou no mundo',
  },
  {
    question: 'Qual atriz protagonizou "Crash Landing on You" ao lado de Hyun Bin?',
    options: ['Park Min-young', 'Son Ye-jin', 'Kim Ji-won', 'Shin Min-a'],
    correct: 1,
    explanation: 'Son Ye-jin interpretou Yoon Se-ri. Ela e Hyun Bin se casaram na vida real em 2022.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Em "Goblin", qual ator interpreta o imortal Goblin?',
    options: ['Lee Min-ho', 'Hyun Bin', 'Gong Yoo', 'Ji Chang-wook'],
    correct: 2,
    explanation: 'Gong Yoo interpretou Kim Shin, o Goblin imortal, em "Guardian: The Lonely and Great God" (2016-2017).',
    category: 'k-drama', difficulty: 'easy',
    relatedHref: '/blog/gong-yoo-ator-goblin-train-to-busan',
    relatedLabel: 'Gong Yoo: do café ao apocalipse zumbi',
  },
  {
    question: 'Em qual drama Lee Min-ho interpretou Gu Jun-pyo?',
    options: ['The King: Eternal Monarch', 'Boys Over Flowers', 'Legend of the Blue Sea', 'City Hunter'],
    correct: 1,
    explanation: '"Boys Over Flowers" (2009) tornou Lee Min-ho famoso internacionalmente.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Em "My Love from the Star", de qual planeta vem o personagem Do Min-joon?',
    options: ['Marte', 'KMT 184.05', 'Andrômeda', 'Nibiru'],
    correct: 1,
    explanation: 'Do Min-joon veio do planeta KMT 184.05, chegando à Terra em 1609.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Em qual plataforma de streaming estreou "Squid Game"?',
    options: ['Disney+', 'HBO Max', 'Netflix', 'Apple TV+'],
    correct: 2,
    explanation: '"Squid Game" estreou na Netflix em setembro de 2021, tornando-se a série mais assistida da plataforma.',
    category: 'k-drama', difficulty: 'easy',
  },
  {
    question: 'Qual ator estrelou tanto "Goblin" quanto "Train to Busan"?',
    options: ['Lee Min-ho', 'Park Seo-joon', 'Gong Yoo', 'Ji Chang-wook'],
    correct: 2,
    explanation: 'Gong Yoo estrelou "Goblin" (2016) e "Train to Busan" (2016), dois marcos do entretenimento coreano.',
    category: 'k-drama', difficulty: 'easy',
    relatedHref: '/blog/gong-yoo-ator-goblin-train-to-busan',
    relatedLabel: 'Gong Yoo: do café ao apocalipse zumbi',
  },
  {
    question: 'Em "Queen of Tears", quem interpreta o protagonista Baek Hyun-woo?',
    options: ['Lee Min-ho', 'Kim Soo-hyun', 'Park Bo-gum', 'Song Joong-ki'],
    correct: 1,
    explanation: 'Kim Soo-hyun interpretou Baek Hyun-woo em "Queen of Tears" (2024), drama que quebrou recordes no tvN.',
    category: 'k-drama', difficulty: 'medium',
    relatedHref: '/blog/queen-of-tears-drama-netflix-recordes-2024',
    relatedLabel: 'Queen of Tears: por que quebrou todos os recordes',
  },
  {
    question: 'Qual drama é baseado no webtoon de Yaongyi e estrelou Cha Eun-woo?',
    options: ['True Beauty', 'Itaewon Class', 'Extraordinary Attorney Woo', 'Weightlifting Fairy'],
    correct: 0,
    explanation: '"True Beauty" (2020) é baseado no webtoon de Yaongyi e estrelou Moon Ga-young e Cha Eun-woo do ASTRO.',
    category: 'k-drama', difficulty: 'medium',
    relatedHref: '/blog/webtoons-que-viraram-kdramas-lista-onde-assistir',
    relatedLabel: 'Webtoons que viraram K-Dramas',
  },
  {
    question: 'Qual ator ganhou o Globo de Ouro por "Squid Game", sendo o primeiro sul-coreano a vencer?',
    options: ['Lee Byung-hun', 'Wi Ha-joon', 'Oh Yeong-su', 'Park Hae-soo'],
    correct: 2,
    explanation: 'Oh Yeong-su ganhou o Globo de Ouro de Melhor Ator Coadjuvante em 2022 pelo papel do Jogador 001.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual K-Drama de 2022 sobre uma advogada com autismo fez sucesso global?',
    options: ['Business Proposal', 'Extraordinary Attorney Woo', 'Our Blues', 'Twenty-Five Twenty-One'],
    correct: 1,
    explanation: '"Extraordinary Attorney Woo" estrelou Park Eun-bin e entrou no Top 10 da Netflix em mais de 50 países.',
    category: 'k-drama', difficulty: 'easy',
    relatedHref: '/blog/park-eun-bin-atriz-uma-advogada-extraordinaria',
    relatedLabel: 'Park Eun-bin: de atriz mirim ao fenômeno global',
  },
  {
    question: 'Qual drama retrata pais obcecados em fazer os filhos entrarem nas melhores universidades?',
    options: ['Sky Castle', 'Reply 1988', 'School 2015', 'Weightlifting Fairy'],
    correct: 0,
    explanation: '"SKY Castle" (2018-2019) satiriza a pressão extrema da educação coreana e as famílias ricas de Seul.',
    category: 'k-drama', difficulty: 'hard',
  },
  {
    question: 'Qual ator interpretou o personagem Ji Pyeong em "Start-Up" (2020)?',
    options: ['Nam Joo-hyuk', 'Kim Seon-ho', 'Suho (EXO)', 'Choi Woo-shik'],
    correct: 1,
    explanation: 'Kim Seon-ho interpretou Han Ji-pyeong, personagem que criou um dos maiores "second lead syndromes" da história dos K-Dramas.',
    category: 'k-drama', difficulty: 'medium',
  },

  // ─── Cultura ──────────────────────────────────────────────────────────────
  {
    question: 'O que significa "Hallyu"?',
    options: ['Música coreana', 'Onda coreana', 'Cultura pop', 'Drama coreano'],
    correct: 1,
    explanation: '"Hallyu" (한류) significa literalmente "Onda Coreana" e se refere ao fenômeno global de expansão da cultura pop sul-coreana.',
    category: 'cultura', difficulty: 'easy',
    relatedHref: '/blog/como-o-kpop-conquistou-o-brasil-historia-numeros',
    relatedLabel: 'Como o K-Pop conquistou o Brasil',
  },
  {
    question: 'O que é "aegyo" na cultura coreana?',
    options: ['Um estilo de dança', 'Um gênero musical', 'Comportamento fofo e encantador', 'Um tipo de maquiagem'],
    correct: 2,
    explanation: '"Aegyo" (애교) se refere a um comportamento deliberadamente fofo e encantador.',
    category: 'cultura', difficulty: 'easy',
    relatedHref: '/blog/aegyo-o-que-e-cultura-coreana',
    relatedLabel: 'Aegyo: o que é e por que divide opiniões',
  },
  {
    question: 'O que é "daebak" em coreano?',
    options: ['Que pena!', 'Incrível / que sorte!', 'Obrigado', 'Com licença'],
    correct: 1,
    explanation: '"Daebak" (대박) significa algo incrível ou uma grande sorte. É muito usada em K-Dramas e pelo fandom.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'Qual é a capital da Coreia do Sul, cenário de grande parte dos K-Dramas?',
    options: ['Busan', 'Incheon', 'Seul', 'Daegu'],
    correct: 2,
    explanation: 'Seul (서울) é a capital e maior cidade da Coreia do Sul, com cerca de 10 milhões de habitantes.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'O que é "mukbang"?',
    options: ['Dança coreana tradicional', 'Transmissão ao vivo comendo grandes quantidades de comida', 'Estilo de maquiagem', 'Música folclórica'],
    correct: 1,
    explanation: '"Mukbang" (먹방) combina os termos para "comer" e "transmissão" em coreano.',
    category: 'cultura', difficulty: 'easy',
  },
  {
    question: 'O que é o sistema de trainee no K-Pop?',
    options: ['Sistema de avaliação de fãs', 'Treinamento intensivo de futuros artistas', 'Programa de bolsas', 'Contrato de distribuição'],
    correct: 1,
    explanation: 'Trainees passam anos treinando canto, dança e idiomas em agências antes de debutar como ídolos.',
    category: 'cultura', difficulty: 'easy',
    relatedHref: '/blog/contrato-idol-coreia-do-sul-como-funciona',
    relatedLabel: 'Como funciona um contrato de idol',
  },
  {
    question: 'Qual bairro de Seul é famoso pela vida cultural e K-Pop?',
    options: ['Gangnam', 'Hongdae', 'Itaewon', 'Insadong'],
    correct: 1,
    explanation: 'Hongdae, ao redor da Universidade Hongik, é famoso por arte de rua, lojas de K-Pop e eventos culturais.',
    category: 'cultura', difficulty: 'medium',
  },
  {
    question: 'Qual é o nome da prática ilegal de comprar álbuns em massa para manipular charts?',
    options: ['Sajaegi', 'Melon Chart', 'Mubank', 'Daesang'],
    correct: 0,
    explanation: '"Sajaegi" (사재기) é a compra ilegal de álbuns ou streams em massa. Já gerou diversos escândalos no K-Pop.',
    category: 'cultura', difficulty: 'hard',
  },
  {
    question: 'Qual é o significado de "oppa" quando usado por uma mulher?',
    options: ['Irmão mais novo', 'Irmão mais velho / homem mais velho próximo', 'Amigo', 'Namorado'],
    correct: 1,
    explanation: '"Oppa" (오빠) é usado por mulheres para se referir a um homem mais velho com quem têm proximidade.',
    category: 'cultura', difficulty: 'easy',
    relatedHref: '/blog/oppa-unnie-hyung-noona-termos-coreanos-guia',
    relatedLabel: 'Oppa, unnie, hyung, noona: guia completo',
  },
  {
    question: 'O que é "Daesang" no K-Pop?',
    options: ['Um tipo de dança', 'O prêmio máximo das cerimônias musicais', 'Um festival de música', 'Uma gravadora independente'],
    correct: 1,
    explanation: '"Daesang" (대상) significa "Grande Prêmio". É o prêmio máximo em cerimônias como MAMA e Golden Disc.',
    category: 'cultura', difficulty: 'medium',
  },
  {
    question: 'Qual é o prato coreano feito de repolho fermentado com pimenta?',
    options: ['Bibimbap', 'Kimchi', 'Japchae', 'Tteokbokki'],
    correct: 1,
    explanation: 'Kimchi (김치) é o prato mais icônico da culinária coreana: vegetais fermentados temperados com pasta de pimenta.',
    category: 'cultura', difficulty: 'easy',
    relatedHref: '/blog/fermentados-coreanos-kimchi-doenjang-ganjang',
    relatedLabel: 'Fermentados coreanos: kimchi e além',
  },
  {
    question: 'Qual conceito do K-Pop se refere à persona pública cultivada pelos ídolos?',
    options: ['Aegyo', 'Idol persona', 'Han', 'Jeong'],
    correct: 1,
    explanation: 'A "idol persona" é a imagem cuidadosamente construída pelas agências para o público.',
    category: 'cultura', difficulty: 'medium',
    relatedHref: '/blog/idol-vs-artist-diferenca-carreira-kpop',
    relatedLabel: 'Idol vs. Artist: a diferença que define carreiras',
  },
  {
    question: 'O que é "Han" (한) na cultura coreana?',
    options: ['Um tipo de música tradicional', 'Sentimento profundo de melancolia e resiliência coletiva', 'Festival de Ano Novo', 'Sistema de escrita coreano'],
    correct: 1,
    explanation: '"Han" é um conceito cultural coreano que descreve uma emoção complexa de tristeza, ressentimento e esperança — muito presente nas artes e na história coreana.',
    category: 'cultura', difficulty: 'hard',
  },
  {
    question: 'O que significa "comeback" no contexto do K-Pop?',
    options: ['Retorno após saída de grupo', 'Lançamento de novo álbum/single por um artista já ativo', 'Volta de grupo inativo', 'Novo contrato com agência'],
    correct: 1,
    explanation: 'No K-Pop, "comeback" é usado para qualquer novo lançamento de um artista ativo, não necessariamente um retorno após ausência.',
    category: 'cultura', difficulty: 'medium',
  },
  {
    question: 'Qual é o sistema de escrita coreano chamado?',
    options: ['Kanji', 'Hangeul', 'Hiragana', 'Hanja'],
    correct: 1,
    explanation: 'O Hangeul (한글) foi criado pelo Rei Sejong em 1443 e é considerado um dos sistemas de escrita mais científicos do mundo.',
    category: 'cultura', difficulty: 'easy',
  },

  // ─── História ─────────────────────────────────────────────────────────────
  {
    question: 'Em que ano o PSY lançou "Gangnam Style", música que viralizou globalmente?',
    options: ['2010', '2011', '2012', '2013'],
    correct: 2,
    explanation: '"Gangnam Style" foi lançado em julho de 2012 e se tornou o primeiro vídeo no YouTube a atingir 1 bilhão de visualizações.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual K-Drama histórico (sageuk) é um dos mais amados de todos os tempos?',
    options: ['Goblin', 'Jewel in the Palace (Dae Jang Geum)', 'Signal', 'Reply 1988'],
    correct: 1,
    explanation: '"Jewel in the Palace" (2003) foi transmitido em mais de 90 países, tornando-se marco na exportação de dramas coreanos.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual ator sul-coreano protagonizou o filme "Parasita", vencedor do Oscar 2020?',
    options: ['Lee Byung-hun', 'Song Kang-ho', 'Choi Min-sik', 'Ha Jung-woo'],
    correct: 1,
    explanation: 'Song Kang-ho é o protagonista de "Parasita" (기생충). O filme ganhou o Oscar de Melhor Filme em 2020.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Qual grupo é conhecido pelo conceito "School Trilogy" em seus primeiros álbuns?',
    options: ['SHINee', 'BTS', 'INFINITE', 'B.A.P'],
    correct: 1,
    explanation: 'O BTS iniciou com a "School Trilogy" (2013-2014), abordando temas de juventude e pressão escolar.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual é o estilo musical popular mais antigo da Coreia que influenciou o K-Pop?',
    options: ['Pansori', 'Trot', 'Gagok', 'Minyo'],
    correct: 1,
    explanation: 'O Trot (트로트) experimentou um grande revival nos anos 2020 e é o gênero popular mais antigo da Coreia.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual grupo de K-Pop foi o primeiro a se apresentar no Grammy Awards?',
    options: ['EXO', 'BIGBANG', 'BTS', 'SHINee'],
    correct: 2,
    explanation: 'O BTS se apresentou no Grammy Awards em 2021, sendo o primeiro grupo sul-coreano a fazê-lo.',
    category: 'história', difficulty: 'medium',
  },
  {
    question: 'Qual foi o primeiro artista coreano a atingir 1 bilhão de views no YouTube?',
    options: ['BTS', 'BIGBANG', 'PSY', "Girls' Generation"],
    correct: 2,
    explanation: 'PSY foi o primeiro com "Gangnam Style" em 2012 — também o primeiro vídeo de qualquer artista a atingir essa marca.',
    category: 'história', difficulty: 'easy',
  },
  {
    question: 'Em que ano a SM Entertainment lançou o H.O.T., considerado o primeiro grupo de K-Pop moderno?',
    options: ['1992', '1996', '1999', '2003'],
    correct: 1,
    explanation: 'H.O.T. (High-five Of Teenagers) debutou em 1996 e é amplamente considerado o grupo que definiu a era moderna do K-Pop.',
    category: 'história', difficulty: 'hard',
  },
  {
    question: 'Qual diretor sul-coreano ganhou 4 Oscars com "Parasita" em 2020, incluindo Melhor Filme?',
    options: ['Park Chan-wook', 'Kim Jee-woon', 'Bong Joon-ho', 'Lee Chang-dong'],
    correct: 2,
    explanation: 'Bong Joon-ho ganhou 4 Oscars na mesma cerimônia: Melhor Filme, Melhor Diretor, Melhor Roteiro Original e Melhor Filme Internacional.',
    category: 'história', difficulty: 'medium',
  },
]

async function main() {
  console.log(`Inserindo ${questions.length} perguntas...`)

  let inserted = 0
  for (const q of questions) {
    await prisma.quizQuestion.upsert({
      where: { id: `seed-quiz-${q.question.slice(0, 30).replace(/\W+/g, '-')}` },
      update: {},
      create: {
        id: `seed-quiz-${q.question.slice(0, 30).replace(/\W+/g, '-')}`,
        question: q.question,
        options: q.options,
        correct: q.correct,
        explanation: q.explanation,
        category: q.category,
        difficulty: q.difficulty,
        relatedHref: q.relatedHref ?? null,
        relatedLabel: q.relatedLabel ?? null,
        isActive: true,
      },
    })
    inserted++
  }

  console.log(`✅ ${inserted} perguntas inseridas`)
}

main().catch(console.error).finally(() => pool.end())
