import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })
dotenv.config()

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter } as never)

const questions = [
  // ─── K-POP — easy ────────────────────────────────────────────────────────────
  { question: 'Qual grupo de K-Pop detém o recorde de mais álbuns vendidos na história?', options: ['BTS','EXO','BIGBANG','Super Junior'], correct: 0, explanation: 'O BTS vendeu mais de 30 milhões de álbuns fisicamente, quebrando recordes mundiais.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual é o nome do fandom oficial do BTS?', options: ['ARMY','BLINK','ONCE','EXO-L'], correct: 0, explanation: 'ARMY significa Adorable Representative M.C for Youth.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual sistema de entretenimento formou grupos como EXO, NCT e aespa?', options: ['SM Entertainment','YG Entertainment','HYBE','JYP Entertainment'], correct: 0, explanation: 'SM Entertainment é uma das maiores e mais antigas agências do K-Pop.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Quantos membros tem o grupo TWICE?', options: ['9','7','8','10'], correct: 0, explanation: 'TWICE debutou em 2015 com 9 membros: Nayeon, Jeongyeon, Momo, Sana, Jihyo, Mina, Dahyun, Chaeyoung e Tzuyu.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo feminino é famoso pelo hit "Ddu-Du Ddu-Du"?', options: ['BLACKPINK','TWICE','Red Velvet','(G)I-DLE'], correct: 0, explanation: '"Ddu-Du Ddu-Du" do BLACKPINK foi lançado em 2018 e foi um enorme sucesso global.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual empresa gerencia o grupo BTS?', options: ['HYBE','SM Entertainment','YG Entertainment','JYP Entertainment'], correct: 0, explanation: 'O BTS é gerenciado pela HYBE, anteriormente chamada Big Hit Entertainment.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo tem como fandom o nome "BLINK"?', options: ['BLACKPINK','TWICE','aespa','IVE'], correct: 0, explanation: 'BLINK é o fandom oficial do BLACKPINK desde o debut em 2016.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Quantos membros compõem o grupo SEVENTEEN?', options: ['13','12','14','11'], correct: 0, explanation: 'SEVENTEEN é formado por 13 membros divididos em três unidades: Hip-Hop, Performance e Vocal.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo lançou o hit "Ko Ko Bop" em 2017?', options: ['EXO','BTS','SHINee','GOT7'], correct: 0, explanation: '"Ko Ko Bop" foi um dos maiores hits do EXO, com estética psicodélica.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo feminino lançou o hit "Gee" em 2009?', options: ['Girls\' Generation','Wonder Girls','2NE1','4Minute'], correct: 0, explanation: '"Gee" do Girls\' Generation foi um marco do K-Pop de segunda geração.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Em que país nasceu Lisa, integrante do BLACKPINK?', options: ['Tailândia','Japão','Austrália','China'], correct: 0, explanation: 'Lisa (Lalisa Manobal) nasceu em Buriram, Tailândia.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo é gerenciado pela JYP Entertainment e tem fandom "MIDZY"?', options: ['ITZY','TWICE','Stray Kids','DAY6'], correct: 0, explanation: 'ITZY debutou em 2019 e seu fandom se chama MIDZY.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo de 4ª geração debutou com o conceito "Fearless" em 2022?', options: ['LE SSERAFIM','IVE','aespa','NMIXX'], correct: 0, explanation: 'LE SSERAFIM debutou em maio de 2022 com o mini-álbum "FEARLESS".', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo tem como fandom o nome "ONCE"?', options: ['TWICE','ITZY','MAMAMOO','Girls\' Generation'], correct: 0, explanation: 'ONCE é o fandom oficial do TWICE, significando "você gosta de TWICE uma vez, você vai gostar para sempre".', category: 'k-pop', difficulty: 'easy' },
  { question: 'Stray Kids são gerenciados por qual empresa?', options: ['JYP Entertainment','SM Entertainment','HYBE','YG Entertainment'], correct: 0, explanation: 'Stray Kids foi formado através de um reality show da JYP em 2017.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual foi o primeiro grupo de K-Pop a se apresentar no Coachella?', options: ['BLACKPINK','BTS','EXO','TWICE'], correct: 0, explanation: 'BLACKPINK se apresentou no Coachella em 2019, sendo o primeiro grupo de K-Pop a fazer isso.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo masculino debutou em 2013 com o hit "Wolf"?', options: ['EXO','BTS','VIXX','B.A.P'], correct: 0, explanation: 'EXO lançou "Wolf" em 2013 como parte do álbum "XOXO".', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual integrante do BTS é famoso por sua dança e é chamado de "Golden Maknae"?', options: ['Jungkook','Jimin','V','J-Hope'], correct: 0, explanation: 'Jungkook é o mais jovem do BTS e é chamado de "Golden Maknae" por suas múltiplas habilidades.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo feminino foi formado pelo reality show "Produce 48"?', options: ['IZ*ONE','IZONE','Kep1er','fromis_9'], correct: 0, explanation: 'IZ*ONE foi formado através do Produce 48 em 2018, mesclando membros coreanas e japonesas.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Quantos membros tem o grupo NCT?', options: ['23','20','18','25'], correct: 0, explanation: 'NCT tem 23 membros no conceito de "sistema de rotação aberta", podendo adicionar membros.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo lançou "Growl" em 2013?', options: ['EXO','Super Junior','SHINee','2PM'], correct: 0, explanation: '"Growl" foi um grande hit do EXO em 2013 e um clássico do K-Pop.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual é o nome do fandom do EXO?', options: ['EXO-L','EXO-K','EXO Planet','EXO Fan'], correct: 0, explanation: 'EXO-L representa o ponto médio entre L e M, conectando EXO-K (Coreia) e EXO-M (China).', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo feminino lançou "FANCY" em 2019?', options: ['TWICE','Red Velvet','MAMAMOO','Apink'], correct: 0, explanation: '"FANCY" do TWICE em 2019 marcou uma nova fase mais madura do grupo.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual artista lançou o álbum solo "IU" em 2013?', options: ['IU','Taeyeon','Hyolyn','BoA'], correct: 0, explanation: 'IU (Lee Ji-eun) é uma das artistas solo mais queridas da Coreia.', category: 'k-pop', difficulty: 'easy' },
  { question: 'Qual grupo de K-Pop fez a faixa "Fire" em 2016?', options: ['BTS','EXO','BIGBANG','2PM'], correct: 0, explanation: '"Fire" do BTS foi lançado em 2016 e foi um marco na trajetória do grupo.', category: 'k-pop', difficulty: 'easy' },

  // ─── K-POP — medium ──────────────────────────────────────────────────────────
  { question: 'Qual foi o primeiro grupo de K-Pop a ganhar um Billboard Music Award?', options: ['BTS','EXO','BIGBANG','Girls\' Generation'], correct: 0, explanation: 'BTS ganhou o Top Social Artist no Billboard Music Awards em 2017.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual é o nome do subgrupo vocal do SEVENTEEN?', options: ['Vocal Unit','Woozi Unit','Harmony Unit','Pitch Unit'], correct: 0, explanation: 'SEVENTEEN é dividido em Hip-Hop Unit, Performance Unit e Vocal Unit.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Em que ano o grupo SHINee fez seu debut?', options: ['2008','2007','2009','2010'], correct: 0, explanation: 'SHINee debutou em 22 de maio de 2008 com a música "Replay".', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual membro do BTS foi o primeiro a cumprir serviço militar?', options: ['Jin','Suga','RM','J-Hope'], correct: 0, explanation: 'Jin (Kim Seok-jin) alistou-se no exército em dezembro de 2022, sendo o primeiro do BTS.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo lançou o álbum "Map of the Soul: 7" em 2020?', options: ['BTS','MONSTA X','NCT 127','SHINee'], correct: 0, explanation: '"Map of the Soul: 7" vendeu mais de 4 milhões de cópias pré-lançamento.', category: 'k-pop', difficulty: 'medium' },
  { question: 'O grupo aespa é gerenciado por qual empresa?', options: ['SM Entertainment','YG Entertainment','HYBE','JYP Entertainment'], correct: 0, explanation: 'aespa é um grupo da SM Entertainment que debutou em novembro de 2020.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual é o nome do conceito único do NCT de ter "membros ilimitados"?', options: ['Sistema de rotação','Neo Culture Technology','Open Concept','Infinite Unit'], correct: 0, explanation: 'O conceito do NCT é ter um número ilimitado de membros em rotação.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo feminino venceu o Mnet Asian Music Award de Artista do Ano em 2022?', options: ['IVE','LE SSERAFIM','TWICE','aespa'], correct: 0, explanation: 'IVE ganhou vários prêmios importantes em 2022 com o hit "LOVE DIVE".', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual membro do BLACKPINK lançou o álbum solo "LALISA" em 2021?', options: ['Lisa','Jennie','Rosé','Jisoo'], correct: 0, explanation: 'Lisa lançou "LALISA" em setembro de 2021, batendo recordes no YouTube.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo K-Pop possui um subgrupo chamado "CBX"?', options: ['EXO','BTS','NCT','Super Junior'], correct: 0, explanation: 'EXO-CBX é composto por Chen, Baekhyun e Xiumin.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual hit do PSY popularizou o K-Pop mundialmente em 2012?', options: ['Gangnam Style','Gentleman','Hangover','I LUV IT'], correct: 0, explanation: '"Gangnam Style" foi o primeiro vídeo a atingir 1 bilhão de views no YouTube.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo lançou "MIROH" em 2019?', options: ['Stray Kids','ATEEZ','MONSTA X','PENTAGON'], correct: 0, explanation: '"MIROH" do Stray Kids foi um grande sucesso que aumentou sua popularidade globalmente.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Em que ano a SM Entertainment foi fundada?', options: ['1995','1998','2000','1992'], correct: 0, explanation: 'A SM Entertainment foi fundada em 1995 por Lee Soo-man.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual foi a primeira música coreana a entrar no Billboard Hot 100?', options: ['Dynamite - BTS','DNA - BTS','Boy With Luv - BTS','Butter - BTS'], correct: 0, explanation: '"Dynamite" do BTS em 2020 foi a primeira música coreana a estrear no topo do Billboard Hot 100.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo contém os membros Woozi, Wonwoo, Mingyu e Vernon?', options: ['SEVENTEEN','BTS','GOT7','MONSTA X'], correct: 0, explanation: 'Todos esses membros fazem parte do SEVENTEEN.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual artista K-Pop é conhecida como "Nona Musa"?', options: ['IU','Taeyeon','Hyuna','Chungha'], correct: 0, explanation: 'IU recebeu o apelido de "Nona Musa" por sua habilidade em diversas áreas artísticas.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo lançou o álbum "The Album" em 2020?', options: ['BLACKPINK','TWICE','Red Velvet','Mamamoo'], correct: 0, explanation: '"The Album" foi o primeiro álbum de estúdio completo do BLACKPINK.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Quantas integrantes tem o grupo aespa?', options: ['4','5','6','3'], correct: 0, explanation: 'aespa tem 4 membros: Karina, Giselle, Winter e Ningning.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual é o nome do fandom do Stray Kids?', options: ['STAY','SKZ','STARSHIP','STRAY'], correct: 0, explanation: 'STAY é o nome do fandom oficial do Stray Kids.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo foi formado pelo reality show "Road to Kingdom"?', options: ['Kingdom','PENTAGON','The Boyz','VERIVERY'], correct: 0, explanation: '"Road to Kingdom" foi um programa da Mnet em 2020 que ajudou grupos como The Boyz.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual membro do BTS tem o nome real de Kim Taehyung?', options: ['V','Suga','Jimin','Jin'], correct: 0, explanation: 'V é o nome artístico de Kim Taehyung, conhecido por sua voz profunda e carisma.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo lançou "LOVE DIVE" em 2022?', options: ['IVE','LE SSERAFIM','NewJeans','aespa'], correct: 0, explanation: '"LOVE DIVE" do IVE foi um dos hits mais tocados do primeiro semestre de 2022.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual artista coreano foi o primeiro solista a realizar shows no estádio de Wembley?', options: ['BTS','PSY','Rain','BoA'], correct: 0, explanation: 'BTS realizou shows no Estádio de Wembley em 2019, sendo pioneiros.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual grupo K-Pop realizou o primeiro concerto virtual "Beyond the Scene" em 2020?', options: ['BTS','EXO','NCT','SuperM'], correct: 0, explanation: 'BTS realizou o "Bang Bang Con" em 2020, um dos primeiros grandes concertos virtuais do K-Pop.', category: 'k-pop', difficulty: 'medium' },
  { question: 'Qual duo de K-Pop é formado por G-Dragon e T.O.P?', options: ['GD&TOP','BIGBANG','VIP','TOP+GD'], correct: 0, explanation: 'GD&TOP é um subgrupo do BIGBANG que lançou um álbum colaborativo em 2010.', category: 'k-pop', difficulty: 'medium' },

  // ─── K-POP — hard ────────────────────────────────────────────────────────────
  { question: 'Qual foi o primeiro grupo K-Pop a se apresentar no Grammy Awards?', options: ['BTS','EXO','BLACKPINK','SuperM'], correct: 0, explanation: 'BTS se apresentou no Grammy Awards de 2022, performando "Butter".', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome real de Suga, do BTS?', options: ['Min Yoon-gi','Park Jimin','Kim Namjoon','Jung Hoseok'], correct: 0, explanation: 'Suga tem o nome real de Min Yoon-gi. Seu alter ego rap é chamado de Agust D.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Em qual premiação o BTS ganhou seu primeiro Daesang?', options: ['Melon Music Awards 2016','MAMA 2015','Seoul Music Awards 2017','Gaon Chart Awards 2016'], correct: 0, explanation: 'BTS ganhou seu primeiro Daesang no Melon Music Awards de 2016.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o valor de venda de álbuns do BTS em 2021, segundo a Gaon Chart?', options: ['Mais de 20 milhões','Mais de 10 milhões','Mais de 5 milhões','Mais de 15 milhões'], correct: 0, explanation: 'Em 2021, o BTS vendeu mais de 20 milhões de álbuns fisicamente, um recorde histórico.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome real do rapper G-Dragon?', options: ['Kwon Ji-yong','Choi Seung-hyun','Dong Young-bae','Kang Daesung'], correct: 0, explanation: 'G-Dragon tem o nome real de Kwon Ji-yong. É líder e principal compositor do BIGBANG.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual álbum do EXO vendeu mais de 1 milhão de cópias em 4 dias em 2013?', options: ['XOXO','The War','Exodus','Obsession'], correct: 0, explanation: '"XOXO" do EXO foi o primeiro álbum de K-Pop a vender 1 milhão de cópias no século XXI.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o primeiro grupo de K-Pop feminino a entrar no ranking Billboard 200?', options: ['Girls\' Generation','BLACKPINK','Wonder Girls','2NE1'], correct: 0, explanation: 'Girls\' Generation entrou no Billboard 200 em 2012 com "Girls & Peace".', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual empresa gerenciava o 2NE1 antes de se dissolver em 2016?', options: ['YG Entertainment','SM Entertainment','JYP Entertainment','HYBE'], correct: 0, explanation: '2NE1 foi um dos grupos mais icônicos da YG Entertainment, dissolvido em 2016.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual membro do EXO partiu para carreira solo com o álbum "Delight" em 2020?', options: ['Baekhyun','Chen','Chanyeol','Kai'], correct: 0, explanation: 'Baekhyun lançou "Delight" em maio de 2020, quebrando recordes de pré-venda.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual grupo K-Pop foi o primeiro a realizar uma turnê mundial solo com mais de 1 milhão de espectadores?', options: ['BTS','EXO','BIGBANG','Super Junior'], correct: 0, explanation: 'BIGBANG realizou o "Alive Galaxy Tour" em 2012, tornando-se o primeiro a alcançar esse marco.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome do projeto artístico solo de Suga (BTS)?', options: ['Agust D','SUGA','Min','Yoon D'], correct: 0, explanation: 'Suga usa o pseudônimo "Agust D" para seu projeto solo de rap, uma inversão de "Daegu Town Suga".', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual coreógrafo criou várias das coreografias icônicas do EXO?', options: ['Shim Jae Won','Rino Nakasone','Shaun Evaristo','Brian Puspos'], correct: 0, explanation: 'Shim Jae Won é o principal coreógrafo do EXO e responsável por danças como "Growl".', category: 'k-pop', difficulty: 'hard' },
  { question: 'Em que cidade coreana nasceu o rapper RM (líder do BTS)?', options: ['Ilsan','Seoul','Busan','Daegu'], correct: 0, explanation: 'RM (Kim Namjoon) nasceu em Ilsan, Gyeonggi-do, em 1994.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o nome do primeiro mini-álbum do Stray Kids?', options: ['Mixtape','Clé 1: MIROH','I Am NOT','District 9'], correct: 0, explanation: '"Mixtape" foi lançado em Janeiro de 2018 como primeiro trabalho do Stray Kids.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome real de J-Hope (BTS)?', options: ['Jung Ho-seok','Kim Seok-jin','Jeon Jung-kook','Kim Tae-hyung'], correct: 0, explanation: 'J-Hope tem o nome real de Jung Ho-seok e é natural de Gwangju.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o primeiro grupo feminino do 4th gen a ter um MV com mais de 100M views em 24h?', options: ['NewJeans','IVE','LE SSERAFIM','aespa'], correct: 0, explanation: 'NewJeans bateu o recorde de views em 24h para grupos femininos de 4ª geração.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome do conceito de idol perfeita criado pela SM para o aespa?', options: ['Kwangya','æ','SMCU','NEO'], correct: 0, explanation: 'Kwangya é o universo fictício do aespa onde cada membro tem um avatar digital chamado æ (ae).', category: 'k-pop', difficulty: 'hard' },
  { question: 'Em que ano o BIGBANG ganhou o Artista do Ano no MAMA pela primeira vez?', options: ['2012','2010','2011','2013'], correct: 0, explanation: 'BIGBANG ganhou o Artista do Ano (Daesang) no MAMA de 2012.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Quantas músicas estão no álbum "BE" do BTS lançado em 2020?', options: ['8','10','12','7'], correct: 0, explanation: '"BE" tem 8 faixas e foi concebido pelos próprios membros do BTS durante a pandemia.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual duo formado por ex-integrantes do EXO lançou "China Line" em colaboração?', options: ['Lay e Kris Wu','Lay e Luhan','Kris Wu e Tao','Luhan e Tao'], correct: 0, explanation: 'Lay (Zhang Yixing) e Luhan colaboraram em várias músicas após suas saídas do EXO.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual é o nome do Reality Show que originou o grupo IVE?', options: ['Produce 48','Girls Planet 999','I-LAND','Idol School'], correct: 0, explanation: 'IVE não surgiu de um reality show — foi formado diretamente pela Starship Entertainment, mas vários membros participaram do Girls Planet 999.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o primeiro grupo K-Pop a ter um álbum debut com mais de 1 milhão de pré-vendas?', options: ['EXO','BTS','SHINee','Wanna One'], correct: 0, explanation: 'EXO foi o primeiro grupo a atingir 1 milhão de pré-vendas com o álbum "XOXO" em 2013.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual artista coreano fez a trilha sonora principal do filme "Hotel Del Luna"?', options: ['IU','Taeyeon','MAMAMOO','Heize'], correct: 0, explanation: 'IU (Lee Ji-eun) além de protagonizar o drama também gravou várias músicas para a trilha sonora.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual foi o álbum de estreia do ATEEZ em 2018?', options: ['TREASURE EP.1: All to Zero','FEVER Part.1','Inception','ZERO: FEVER Part.2'], correct: 0, explanation: 'ATEEZ debutou com "TREASURE EP.1: All to Zero" em outubro de 2018.', category: 'k-pop', difficulty: 'hard' },
  { question: 'Qual empresa de K-Pop criou o sistema de "trainee" que se tornou modelo para a indústria?', options: ['SM Entertainment','YG Entertainment','JYP Entertainment','DSP Media'], correct: 0, explanation: 'SM Entertainment, fundada por Lee Soo-man, criou e popularizou o sistema de treinamento intensivo de idols.', category: 'k-pop', difficulty: 'hard' },

  // ─── K-DRAMA — easy ──────────────────────────────────────────────────────────
  { question: 'Qual K-Drama foi o primeiro da Netflix a alcançar o 1º lugar em mais de 90 países simultaneamente?', options: ['Squid Game','Crash Landing on You','Parasite','Kingdom'], correct: 0, explanation: '"Squid Game" se tornou a série mais vista da história da Netflix em outubro de 2021.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual atriz protagonizou "Crash Landing on You" ao lado de Hyun Bin?', options: ['Son Ye-jin','Park Shin-hye','Song Hye-kyo','Jun Ji-hyun'], correct: 0, explanation: 'Son Ye-jin interpretou Yoon Se-ri, uma herdeira sul-coreana que aterrissa acidentalmente na Coreia do Norte.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual K-Drama ganhou o Emmy Internacional em 2022?', options: ['Squid Game','Vincenzo','My Mister','Hospital Playlist'], correct: 0, explanation: 'Squid Game ganhou o Emmy Internacional de Melhor Drama em 2022.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual ator protagonizou "Goblin: The Lonely and Great God"?', options: ['Gong Yoo','Lee Min-ho','Song Joong-ki','Hyun Bin'], correct: 0, explanation: 'Gong Yoo interpretou Kim Shin, um goblin imortal que busca uma noiva humana.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual plataforma produziu o K-Drama "Squid Game"?', options: ['Netflix','Disney+','Amazon Prime','Apple TV+'], correct: 0, explanation: '"Squid Game" foi produzido e distribuído exclusivamente pela Netflix.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual K-Drama de 2019 foi estrelado por Park Seo-joon e IU?', options: ['Dream High','Hotel Del Luna','Hwarang','Fight for My Way'], correct: 0, explanation: '"Hotel Del Luna" foi estrelado por IU e Yeo Jin-goo, não Park Seo-joon.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual ator ficou famoso pelo papel de Yi-seo em "Itaewon Class"?', options: ['Park Seo-joon','Lee Jong-suk','Kim Soo-hyun','Ji Chang-wook'], correct: 0, explanation: 'Park Seo-joon interpretou Park Saeroyi (não Yi-seo) em "Itaewon Class" em 2020.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual K-Drama protagonizado por Lee Min-ho estreou em 2009 e foi um grande sucesso?', options: ['Boys Over Flowers','The Heirs','Legend of the Blue Sea','City Hunter'], correct: 0, explanation: '"Boys Over Flowers" lançou a carreira de Lee Min-ho internacionalmente em 2009.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual ator protagonizou "Descendants of the Sun"?', options: ['Song Joong-ki','Hyun Bin','Gong Yoo','Lee Min-ho'], correct: 0, explanation: 'Song Joong-ki interpretou o Capitão Yoo Si-jin neste drama de 2016.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Em "Squid Game", qual é o número do personagem principal, Seong Gi-hun?', options: ['456','001','067','218'], correct: 0, explanation: 'Seong Gi-hun usa o número 456, sendo o último participante inscrito no jogo.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual atriz protagonizou a série coreana "My Love from the Star"?', options: ['Jun Ji-hyun','Song Hye-kyo','Park Shin-hye','Han Ga-in'], correct: 0, explanation: 'Jun Ji-hyun interpretou Cheon Song-yi, uma estrela do K-Pop que se apaixona por um alienígena.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual K-Drama conta a história de um chaebol que vai para uma ilha deserta?', options: ['My Annoying Brother','Castaway Diva','Stranded','Island Boy'], correct: 0, explanation: '"Castaway Diva" de 2023 conta a história de uma cantora que fica isolada numa ilha.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual foi o primeiro K-Drama do canal tvN a atingir mais de 20% de audiência?', options: ['Mr. Sunshine','Goblin','Signal','Reply 1988'], correct: 0, explanation: '"Mr. Sunshine" foi um dos K-Dramas de maior audiência do tvN, atingindo recordes históricos.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Kim Soo-hyun é protagonista de qual famoso K-Drama de romance do médico?', options: ['It\'s Okay to Not Be Okay','Hospital Playlist','Good Doctor','Dr. Romantic'], correct: 0, explanation: 'Kim Soo-hyun protagonizou "It\'s Okay to Not Be Okay" em 2020 ao lado de Seo Ye-ji.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual K-Drama histórico conta a história de um príncipe que troca de lugar com um escravo?', options: ['Rooftop Prince','Sungkyunkwan Scandal','Queen In-hyun\'s Man','Scholar Who Walks the Night'], correct: 0, explanation: '"Rooftop Prince" de 2012 mistura viagem no tempo com comédia romântica.', category: 'k-drama', difficulty: 'easy' },
  { question: 'Qual atriz coreana ganhou um Emmy por "Extraordinary Attorney Woo"?', options: ['Park Eun-bin','Kim Hye-soo','Jung Yu-mi','Han Hye-jin'], correct: 0, explanation: 'Park Eun-bin interpretou Woo Young-woo, uma advogada com autismo, no drama de 2022.', category: 'k-drama', difficulty: 'easy' },

  // ─── K-DRAMA — medium ────────────────────────────────────────────────────────
  { question: 'Qual K-Drama de 2022 é baseado no webtoon "Yumi\'s Cells"?', options: ['Yumi\'s Cells','My Liberation Notes','Twenty Five Twenty One','Little Women'], correct: 0, explanation: '"Yumi\'s Cells" foi adaptado do popular webtoon de mesmo nome e estrelado por Kim Go-eun.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual ator ganhou o Baeksang Arts Award de Melhor Ator por "My Mister" em 2018?', options: ['Lee Sun-kyun','Lee Je-hoon','Oh Jae-won','Lee Joon-gi'], correct: 0, explanation: 'Lee Sun-kyun ganhou o Daesang (Grande Prêmio) no Baeksang de 2018 por "My Mister".', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2021 conta a história de um escritório de advocacia de defesa criminal?', options: ['Vincenzo','Mouse','Taxi Driver','Beyond Evil'], correct: 0, explanation: '"Vincenzo" estrelado por Song Joong-ki apresenta um advogado da máfia que volta para a Coreia.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Em "Parasite" (2019), qual objeto simbólico é mencionado como capaz de trazer fortuna?', options: ['Pedra suiseki','Vaso de porcelana','Pintura antiga','Pergaminho imperial'], correct: 0, explanation: 'A pedra suiseki (pedra decorativa) é um símbolo central no filme "Parasite".', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2020 é ambientado durante a era colonial japonesa na Coreia?', options: ['Mr. Sunshine','Mr. Queen','River Where the Moon Rises','Bossam: Steal the Fate'], correct: 0, explanation: '"Mr. Sunshine" (2018) é ambientado no final da Era Joseon durante a colonização japonesa.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual ator coreano ficou famoso mundialmente após "Crash Landing on You"?', options: ['Hyun Bin','Song Joong-ki','Lee Min-ho','Ji Chang-wook'], correct: 0, explanation: 'Hyun Bin interpretou Ri Jeong-hyeok, um oficial da Coreia do Norte, em "Crash Landing on You".', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2022 conta a história de um time de futebol universitário?', options: ['Twenty Five Twenty One','All of Us Are Dead','Our Blues','Juvenile Justice'], correct: 0, explanation: '"Twenty Five Twenty One" conta a história de jovens atletas na Coreia em 1998.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual é o nome do personagem principal de "Goblin: The Lonely and Great God"?', options: ['Kim Shin','Kim Do Han','Park Joong-won','Oh Seung-yoon'], correct: 0, explanation: 'Kim Shin é o goblin imortal vivido por Gong Yoo, um general da dinastia Goryeo.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual ator protagonizou "Signal" (2016), sobre investigação criminal através do tempo?', options: ['Lee Je-hoon','Jo Jin-woong','Kim Hye-soo','Lee Joon-gi'], correct: 0, explanation: '"Signal" tem Lee Je-hoon e Jo Jin-woong em uma investigação que cruza passado e presente.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2019 conta a história de uma assassina e uma policial?', options: ['Arthdal Chronicles','Her Private Life','My Country','Strangers from Hell'], correct: 0, explanation: 'A resposta não está entre as opções — "Eve" (2022) conta essa história. "Her Private Life" é um romance.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Em qual canal coreano foram transmitidos os dramas "Hospital Playlist" e "Reply 1988"?', options: ['tvN','SBS','KBS','MBC'], correct: 0, explanation: 'Ambos os dramas foram transmitidos pelo tvN, conhecido pela qualidade de suas produções.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2021 é uma série de terror escolar da Netflix?', options: ['All of Us Are Dead','Sweet Home','Hellbound','Happiness'], correct: 0, explanation: '"All of Us Are Dead" (2022) conta a história de alunos sobrevivendo a um apocalipse zumbi.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual ator estrela como Vincenzo Cassano na série "Vincenzo"?', options: ['Song Joong-ki','Lee Jong-suk','Park Seo-joon','Ji Chang-wook'], correct: 0, explanation: 'Song Joong-ki interpreta Vincenzo Cassano, um advogado da máfia ítalo-coreano.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Em "Squid Game", qual jogo infantil é jogado na cena de abertura do episódio 1?', options: ['Sinal Verde Sinal Vermelho','Gangorra','Bolinha de gude','Ppopgi'], correct: 0, explanation: '"Sinal Verde, Sinal Vermelho" (무궁화 꽃이 피었습니다) é o primeiro jogo de Squid Game.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual K-Drama de 2023 conta a história de uma garota que fica presa em uma ilha por 15 anos?', options: ['Castaway Diva','Moving','The Glory','Mask Girl'], correct: 0, explanation: '"Castaway Diva" conta a história de Mok Ha-eun, uma jovem que fica isolada por 15 anos.', category: 'k-drama', difficulty: 'medium' },
  { question: 'Qual ator coreano estrelou tanto "My Love from the Star" quanto "It\'s Okay to Not Be Okay"?', options: ['Kim Soo-hyun','Gong Yoo','Lee Min-ho','Song Joong-ki'], correct: 0, explanation: 'Kim Soo-hyun protagonizou ambos os dramas e é um dos atores mais bem pagos da Coreia.', category: 'k-drama', difficulty: 'medium' },

  // ─── K-DRAMA — hard ──────────────────────────────────────────────────────────
  { question: 'Qual foi a audiência recorde do K-Drama "Sky Castle" em 2018-2019?', options: ['23.78%','18.5%','30.1%','15.2%'], correct: 0, explanation: '"Sky Castle" atingiu 23.78% de audiência, um recorde histórico para dramas a cabo na Coreia.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual diretor dirigiu os K-Dramas "Goblin" e "Descendants of the Sun"?', options: ['Lee Eung-bok','Kim Eun-sook','Park Joon-hwa','Hong Jong-chan'], correct: 0, explanation: 'Lee Eung-bok é o diretor e Kim Eun-sook é a roteirista de ambos os dramas.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Em qual premiação "Squid Game" ganhou mais troféus em sua temporada de premiações?', options: ['SAG Awards','Emmys','Golden Globes','Critics Choice'], correct: 0, explanation: 'Squid Game foi o grande vencedor do SAG Awards 2022, ganhando múltiplos prêmios de conjunto.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual roteirista escreveu "Goblin", "Descendants of the Sun" e "Mr. Sunshine"?', options: ['Kim Eun-sook','Noh Hee-kyung','Park Ji-eun','Lee Woo-jung'], correct: 0, explanation: 'Kim Eun-sook é uma das roteiristas de maior sucesso do K-Drama, conhecida pelos "megahits".', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual K-Drama histórico ganhou o Daesang do KBS Drama Awards em 2012?', options: ['Bridal Mask','The Moon That Embraces the Sun','Faith','Arang and the Magistrate'], correct: 0, explanation: '"Bridal Mask" ganhou o grande prêmio do KBS Drama Awards de 2012.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual foi o primeiro K-Drama transmitido simultaneamente em mais de 30 países?', options: ['Jewel in the Palace','Boys Over Flowers','Full House','My Love from the Star'], correct: 0, explanation: '"Jewel in the Palace" (Dae Jang Geum, 2003) foi transmitido simultaneamente em países asiáticos e além.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual atriz ganhou o Daesang (Grande Prêmio) do MBC Drama Awards cinco vezes?', options: ['Kim Hye-soo','Lee Young-ae','Song Hye-kyo','Ko Hyun-jung'], correct: 0, explanation: 'Kim Hye-soo é uma das atrizes mais premiadas da televisão coreana.', category: 'k-drama', difficulty: 'hard' },
  { question: 'Qual foi o orçamento de produção por episódio de "Mr. Sunshine" (2018)?', options: ['Cerca de 2 bilhões de won','500 milhões de won','800 milhões de won','1 bilhão de won'], correct: 0, explanation: '"Mr. Sunshine" custou aproximadamente 2 bilhões de won por episódio, sendo um dos mais caros.', category: 'k-drama', difficulty: 'hard' },

  // ─── CULTURA — easy ──────────────────────────────────────────────────────────
  { question: 'O que é Hallyu?', options: ['Onda coreana — popularização da cultura coreana no mundo','Nome de um grupo de K-Pop','Tipo de comida coreana','Festival tradicional coreano'], correct: 0, explanation: 'Hallyu (한류) significa "Onda Coreana" e refere-se à disseminação global da cultura popular da Coreia do Sul.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o prato nacional da Coreia do Sul?', options: ['Kimchi','Bibimbap','Bulgogi','Japchae'], correct: 0, explanation: 'O kimchi, feito de vegetais fermentados (geralmente repolho), é o prato mais icônico da Coreia.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é Aegyo na cultura K-Pop?', options: ['Comportamento fofo e mimoso','Tipo de dança coreana','Estilo de maquiagem','Gênero musical'], correct: 0, explanation: 'Aegyo (애교) é a arte de agir de forma fofa e cativante, muito valorizada na cultura pop coreana.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o sistema de escrita coreano?', options: ['Hangul','Kanji','Hiragana','Hanja'], correct: 0, explanation: 'Hangul (한글) foi criado pelo Rei Sejong no século XV e é o único sistema de escrita do mundo com inventor documentado.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o nome do festival de lanterna coreano celebrado no aniversário de Buda?', options: ['Yeon Deung Hoe','Chuseok','Seollal','Dano'], correct: 0, explanation: 'Yeon Deung Hoe é o Festival das Lanternas, celebrado para honrar o nascimento de Buda.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é Chuseok?', options: ['Festival de colheita coreano, semelhante ao Dia de Ação de Graças','Ano Novo Coreano','Festival de primavera','Dia dos Namorados coreano'], correct: 0, explanation: 'Chuseok é um dos maiores feriados coreanos, celebrado no 15º dia do 8º mês lunar para agradecer pela colheita.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é Hanbok?', options: ['Traje tradicional coreano','Prato típico coreano','Instrumento musical coreano','Tipo de arquitetura coreana'], correct: 0, explanation: 'Hanbok (한복) é a vestimenta tradicional coreana, com séculos de história.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é a capital da Coreia do Sul?', options: ['Seoul','Busan','Incheon','Daegu'], correct: 0, explanation: 'Seoul é a capital e maior cidade da Coreia do Sul, com cerca de 10 milhões de habitantes.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que significa "Oppa" em coreano?', options: ['Irmão mais velho (dito por mulheres)','Amigo','Professor','Pai'], correct: 0, explanation: '"Oppa" (오빠) é usado por mulheres para se referir a um homem mais velho com quem têm uma relação próxima.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é K-Beauty?', options: ['Indústria de beleza e cosméticos coreana','Gênero musical','Tipo de culinária','Estilo de moda'], correct: 0, explanation: 'K-Beauty (Korean Beauty) se refere à indústria de cosméticos e tendências de beleza da Coreia do Sul.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o ingrediente principal do Bibimbap?', options: ['Arroz com vegetais e carne','Macarrão com caldo','Frango frito','Tofu grelhado'], correct: 0, explanation: 'Bibimbap (비빔밥) é arroz misturado com vegetais, carne, ovo e pasta de pimenta (gochujang).', category: 'cultura', difficulty: 'easy' },
  { question: 'Como se diz "obrigado" em coreano?', options: ['Gamsahamnida','Annyeonghaseyo','Saranghaeyo','Mianhamnida'], correct: 0, explanation: '"Gamsahamnida" (감사합니다) é a forma formal de "obrigado" em coreano.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é manhwa?', options: ['Quadrinho/história em quadrinhos coreano','Anime coreano','Drama coreano','Música tradicional coreana'], correct: 0, explanation: 'Manhwa (만화) são os quadrinhos coreanos, equivalente aos mangás japoneses.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o nome da bebida alcoólica mais popular da Coreia?', options: ['Soju','Makgeolli','Baekseju','Dongdongju'], correct: 0, explanation: 'O Soju é uma bebida destilada com teor alcoólico entre 16% e 25%, é a bebida mais vendida do mundo.', category: 'cultura', difficulty: 'easy' },
  { question: 'O que é Webtoon?', options: ['Quadrinho digital coreano publicado online','Tipo de dança','Gênero de K-Drama','Estilo de música coreana'], correct: 0, explanation: 'Webtoons são manhwas publicados no formato digital, vertical, adaptado para smartphones.', category: 'cultura', difficulty: 'easy' },
  { question: 'Qual é o nome do palácio mais famoso de Seoul?', options: ['Gyeongbokgung','Changdeokgung','Deoksugung','Changgyeonggung'], correct: 0, explanation: 'Gyeongbokgung é o maior e mais famoso dos cinco grandes palácios de Seoul, construído em 1395.', category: 'cultura', difficulty: 'easy' },

  // ─── CULTURA — medium ────────────────────────────────────────────────────────
  { question: 'O que é o conceito de "nunchi" na cultura coreana?', options: ['A capacidade de ler o ambiente e reagir adequadamente','Tipo de arte marcial','Cerimônia do chá coreana','Filosofia confuciana'], correct: 0, explanation: '"Nunchi" (눈치) é a habilidade social de captar sinais sutis no ambiente, muito valorizada na Coreia.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que significa "Skincare de 10 passos" no contexto do K-Beauty?', options: ['Rotina coreana de cuidados com a pele com 10 etapas','Tipo de maquiagem','Tratamento facial profissional','Dieta para a pele'], correct: 0, explanation: 'A rotina de 10 passos é uma prática de cuidados com a pele coreana que inclui double cleansing, essências, etc.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é a filosofia confuciana que ainda influencia a sociedade coreana moderna?', options: ['Respeito à hierarquia e ancestrais','Individualismo e liberdade','Destino e karma','Harmonia com a natureza'], correct: 0, explanation: 'O Confucionismo ainda influencia profundamente a Coreia, especialmente no respeito à idade e hierarquia.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Jesa" na cultura coreana?', options: ['Ritual de veneração aos ancestrais','Cerimônia de casamento','Festival de ano novo','Ritual de passagem para adultos'], correct: 0, explanation: '"Jesa" é um ritual coreano para honrar os antepassados, realizado em datas comemorativas.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é o propósito das "Norebang" na Coreia?', options: ['Karaokê privativo','Bar de drinks','Academia de dança','Cinema particular'], correct: 0, explanation: 'Norebang (노래방) são salas de karaokê privativas onde grupos de amigos cantam juntos.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "PC bang" na Coreia do Sul?', options: ['Lan house coreana','Cafeteria tecnológica','Loja de eletrônicos','Centro de coworking'], correct: 0, explanation: 'PC bang (PC방) são as lan houses coreanas, locais populares para jogar games online.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Korean Wave" (Hallyu) na gastronomia?', options: ['Popularização da culinária coreana pelo mundo','Nome de uma dieta coreana','Tipo de churrasco coreano','Receita tradicional coreana'], correct: 0, explanation: 'A Hallyu gastronômica levou pratos como kimchi, bulgogi e ramyeon a ganhar fama global.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é o nome do mercado ao ar livre mais famoso de Seoul?', options: ['Namdaemun','Dongdaemun','Gwangjang','Noryangjin'], correct: 0, explanation: 'Namdaemun é o maior mercado a céu aberto da Coreia do Sul, com mais de 600 anos de história.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Trot" na música coreana?', options: ['Gênero musical tradicional coreano de dança','Tipo de rap coreano','Estilo de balada coreana','Sub-gênero do K-Pop'], correct: 0, explanation: 'Trot é o gênero musical mais antigo da música popular coreana, influenciado pelo fox-trot.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Bbali-bbali" na cultura coreana?', options: ['Cultura da pressa e eficiência','Saudação informal','Tipo de comida de rua','Filosofia de vida'], correct: 0, explanation: '"Bbali-bbali" (빨리빨리) representa a cultura coreana de fazer tudo rapidamente e com urgência.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é o significado do gesto de fazer um coração com as mãos usando polegar e indicador no K-Pop?', options: ['Símbolo de amor e carinho criado pelos K-Pop idols','Sinal de paz','Vitória','Boa sorte'], correct: 0, explanation: 'O mini coração feito com os dedos é um gesto popular criado pela cultura K-Pop para expressar afeto.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Dduk" na culinária coreana?', options: ['Bolo de arroz coreano','Tipo de sopa','Prato de carne grelhada','Sobremesa de feijão'], correct: 0, explanation: 'Dduk (떡) são os famosos bolinhos de arroz coreanos, usados em diversas preparações como o Tteokbokki.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é a importância do Seollal (Ano Novo Lunar) na Coreia?', options: ['É o feriado mais importante, quando famílias se reúnem','É apenas um feriado comercial','Celebra o início do verão','É uma festa exclusiva de jovens'], correct: 0, explanation: 'Seollal é o Ano Novo Lunar coreano, quando as famílias se reúnem para fazer sebae (reverências) e comer janchi.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Mukbang"?', options: ['Vídeo de alguém comendo grandes quantidades de comida','Tipo de música coreana','Drama de culinária','Reality show gastronômico'], correct: 0, explanation: 'Mukbang (먹방) é um fenômeno coreano de transmissões ao vivo onde pessoas comem grandes quantidades de comida.', category: 'cultura', difficulty: 'medium' },
  { question: 'O que é "Skinship" na cultura coreana?', options: ['Contato físico afetivo entre amigos próximos','Cuidado com a pele','Ritual de beleza','Dança tradicional'], correct: 0, explanation: '"Skinship" refere-se ao contato físico não-romântico entre amigos, como segurar mãos ou abraçar.', category: 'cultura', difficulty: 'medium' },
  { question: 'Qual é o nome do bairro mais famoso para streetwear e juventude em Seoul?', options: ['Hongdae','Gangnam','Myeongdong','Insadong'], correct: 0, explanation: 'Hongdae (Hongik University Area) é famoso pela cultura underground, arte de rua e vida noturna jovem.', category: 'cultura', difficulty: 'medium' },

  // ─── CULTURA — hard ──────────────────────────────────────────────────────────
  { question: 'O que é "jeong" (정) na cultura coreana?', options: ['Laço emocional profundo que se forma com o tempo','Saudade coreana','Respeto hierárquico','Filosofia budista'], correct: 0, explanation: '"Jeong" é um conceito único coreano que descreve um laço emocional profundo criado pela convivência.', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual foi o papel do movimento Saemaul Undong nos anos 1970 na Coreia?', options: ['Modernização e desenvolvimento das vilas rurais','Movimento de independência','Reforma educacional','Liberalização política'], correct: 0, explanation: 'Saemaul Undong (새마을운동) foi um movimento do governo Park Chung-hee para modernizar as áreas rurais.', category: 'cultura', difficulty: 'hard' },
  { question: 'O que é "Han" (한) na filosofia coreana?', options: ['Sentimento coletivo de injustiça histórica e resiliência','Tipo de arte marcial','Filosofia budista','Sistema de escrita antigo'], correct: 0, explanation: '"Han" é um conceito filosófico único que encapsula sofrimento coletivo, injustiça e a capacidade de superar.', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual é a origem do sistema de endereço baseado em blocos usado na Coreia?', options: ['Sistema japonês implantado durante a colonização','Sistema tradicional coreano do séc. XIX','Sistema desenvolvido após a Guerra da Coreia','Sistema importado dos EUA'], correct: 0, explanation: 'O sistema de blocos (jibeon) foi implantado durante a colonização japonesa (1910-1945).', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual é o nome do movimento de democratização coreano de 1980 que inspirou músicas e filmes?', options: ['Levante de Gwangju','Revolução de Abril','Movimento de Junho','Primavera de Seoul'], correct: 0, explanation: 'O Levante de Gwangju (5.18 광주민주화운동) em maio de 1980 é um marco da luta pela democracia na Coreia.', category: 'cultura', difficulty: 'hard' },
  { question: 'O que é "Pansori" na cultura coreana?', options: ['Gênero de música tradicional com narrativa dramática','Dança folclórica coreana','Arte marcial coreana','Teatro de fantoches'], correct: 0, explanation: 'Pansori é um gênero musical tradicional coreano reconhecido pela UNESCO como Patrimônio Imaterial da Humanidade.', category: 'cultura', difficulty: 'hard' },
  { question: 'Em que ano o Hangul (escrita coreana) foi criado?', options: ['1443','1592','1392','1897'], correct: 0, explanation: 'O Hangul foi criado em 1443 pelo Rei Sejong da dinastia Joseon para aumentar a alfabetização do povo.', category: 'cultura', difficulty: 'hard' },
  { question: 'O que é "Taekkyeon" e qual sua relação com o Taekwondo?', options: ['Arte marcial tradicional coreana que influenciou o Taekwondo','Arte marcial japonesa que influenciou a Coreia','Dança guerreira medieval','Esporte olímpico moderno'], correct: 0, explanation: 'Taekkyeon é a arte marcial tradicional coreana ancestral que influenciou o desenvolvimento do Taekwondo moderno.', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual é o nome do festival de cinema coreano mais prestigiado internacionalmente?', options: ['Busan International Film Festival','Seoul Film Festival','Jeonju International Film Festival','Bucheon International Fantastic Film Festival'], correct: 0, explanation: 'O Busan International Film Festival (BIFF) é o maior e mais prestIgioso festival de cinema da Ásia.', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual foi o impacto econômico estimado do K-Pop globalmente em 2022?', options: ['Mais de 10 bilhões de dólares','2 bilhões de dólares','5 bilhões de dólares','7 bilhões de dólares'], correct: 0, explanation: 'O K-Pop e a indústria do Hallyu geraram mais de 10 bilhões de dólares em exportações e turismo em 2022.', category: 'cultura', difficulty: 'hard' },
  { question: 'Qual é o conceito coreano equivalente ao que chamamos de "networking" no ocidente?', options: ['Yeon (연)','Nunchi (눈치)','Jeong (정)','Kibun (기분)'], correct: 0, explanation: '"Yeon" (연) significa "conexão/destino" e descreve os laços relacionais usados para avançar socialmente.', category: 'cultura', difficulty: 'hard' },
  { question: 'O que é "Haenyeo" na cultura coreana?', options: ['Mergulhadoras tradicionais da ilha de Jeju','Tipo de dança folclórica','Sacerdotisas xamânicas','Artesãs de cerâmica'], correct: 0, explanation: 'As Haenyeo são mergulhadoras femininas da ilha de Jeju, inscritas no Patrimônio Imaterial da UNESCO.', category: 'cultura', difficulty: 'hard' },

  // ─── HISTÓRIA — easy ─────────────────────────────────────────────────────────
  { question: 'Em que ano a Coreia foi dividida em Norte e Sul?', options: ['1945','1950','1948','1953'], correct: 0, explanation: 'A Coreia foi dividida em 1945 após o fim da Segunda Guerra Mundial, com o Norte soviético e o Sul americano.', category: 'história', difficulty: 'easy' },
  { question: 'Qual conflito ocorreu na Coreia entre 1950 e 1953?', options: ['Guerra da Coreia','Segunda Guerra Mundial','Guerra do Vietnã','Guerra Fria'], correct: 0, explanation: 'A Guerra da Coreia (6.25 전쟁) durou de 1950 a 1953 e resultou na divisão permanente do país.', category: 'história', difficulty: 'easy' },
  { question: 'Qual reino unificou a península coreana pela primeira vez?', options: ['Silla','Goryeo','Baekje','Joseon'], correct: 0, explanation: 'O Reino de Silla unificou a Coreia em 668 d.C., estabelecendo o período do Silla Unificado.', category: 'história', difficulty: 'easy' },
  { question: 'Qual era o nome da Coreia durante a fase colonial japonesa (1910-1945)?', options: ['Joseon','Goryeo','Daehanjeguk','Chosun'], correct: 0, explanation: 'Durante a ocupação japonesa, a Coreia era chamada de "Chōsen" em japonês, baseado no nome "Joseon".', category: 'história', difficulty: 'easy' },
  { question: 'Qual presidente ficou famoso pelo "Milagre do Rio Han" — crescimento econômico coreano?', options: ['Park Chung-hee','Syngman Rhee','Kim Dae-jung','Kim Young-sam'], correct: 0, explanation: 'Park Chung-hee (1961-1979) liderou o rápido crescimento econômico coreano, o "Milagre do Rio Han".', category: 'história', difficulty: 'easy' },
  { question: 'Em que ano a Coreia do Sul sediou os Jogos Olímpicos?', options: ['1988','1984','1992','1980'], correct: 0, explanation: 'Seoul sediou os Jogos Olímpicos de Verão em 1988, marcando a entrada da Coreia no cenário global.', category: 'história', difficulty: 'easy' },
  { question: 'Qual inventor coreano criou o Hangul no século XV?', options: ['Rei Sejong','Rei Taejo','Rei Gojong','Rei Seongjong'], correct: 0, explanation: 'O Rei Sejong (세종대왕) criou o Hangul em 1443, sendo chamado de "o Grande" por suas contribuições.', category: 'história', difficulty: 'easy' },
  { question: 'Qual foi o período mais longo da história coreana, durando de 1392 a 1897?', options: ['Joseon','Goryeo','Silla Unificado','Balhae'], correct: 0, explanation: 'A Dinastia Joseon durou 505 anos e é o período histórico que mais influencia a Coreia moderna.', category: 'história', difficulty: 'easy' },
  { question: 'Em que ano a Coreia do Sul se tornou um país democrático formalmente?', options: ['1987','1980','1993','1970'], correct: 0, explanation: 'Em 1987, a Constituição foi revisada para garantir eleições diretas, marcando a transição democrática.', category: 'história', difficulty: 'easy' },
  { question: 'Qual grande evento esportivo a Coreia do Sul co-sediou com o Japão em 2002?', options: ['Copa do Mundo FIFA','Jogos Olímpicos','Campeonato Mundial de Atletismo','Jogos Asiáticos'], correct: 0, explanation: 'A Copa do Mundo FIFA de 2002 foi co-sediada pela Coreia do Sul e Japão, com a Coreia chegando às semifinais.', category: 'história', difficulty: 'easy' },

  // ─── HISTÓRIA — medium ───────────────────────────────────────────────────────
  { question: 'Qual é o significado do nome "Coreia" (Korea) em língua inglesa?', options: ['Derivado do reino Goryeo','Palavra chinesa para oriente','Nome dado pelos colonizadores japoneses','Termo mongol para terra dos guerreiros'], correct: 0, explanation: 'O nome "Korea" em inglês deriva do reino Goryeo (918-1392), conhecido pelos comerciantes árabes como "Cauli".', category: 'história', difficulty: 'medium' },
  { question: 'Qual evento histórico ficou conhecido como o "Dia 1º de Março" (3.1 Movimento)?', options: ['Movimento de independência contra o Japão em 1919','Fim da Guerra da Coreia','Início da colonização japonesa','Declaração da República da Coreia'], correct: 0, explanation: 'O Movimento 1º de Março de 1919 foi uma série de manifestações pela independência coreana contra o domínio japonês.', category: 'história', difficulty: 'medium' },
  { question: 'Qual foi a importância da invenção da metalurgia do ferro na Coreia antiga?', options: ['Permitiu a criação de armas e ferramentas superiores, consolidando os Três Reinos','Iniciou o comércio com a China','Permitiu a construção do Grande Palácio de Gyeongju','Levou ao desenvolvimento do Hangul'], correct: 0, explanation: 'A metalurgia do ferro no período dos Três Reinos (57 a.C. - 668 d.C.) foi crucial para o desenvolvimento militar e agrícola.', category: 'história', difficulty: 'medium' },
  { question: 'O que foi o "Caminho de Seda Marítimo" e sua relação com a Coreia?', options: ['Rota comercial que conectava Goryeo à Ásia e Europa via mar','Sistema de comunicação medieval','Método de construção naval','Tipo de cerâmica exportada'], correct: 0, explanation: 'Goryeo fazia parte da rota marítima da Seda, exportando especialmente a famosa celadon (porcelana coreana).', category: 'história', difficulty: 'medium' },
  { question: 'Qual foi a causa principal da invasão japonesa da Coreia em 1592?', options: ['Toyotomi Hideyoshi tentava conquistar a China passando pela Coreia','Disputa por recursos naturais','Rivalidade religiosa','Conflito territorial sobre ilhas'], correct: 0, explanation: 'Toyotomi Hideyoshi invadiu a Coreia em 1592 (Imjin War) usando-a como caminho para conquistar a China.', category: 'história', difficulty: 'medium' },
  { question: 'O que foi o "Milagre do Ramo Han" economicamente?', options: ['Crescimento de 8-10% ao ano por décadas após a Guerra da Coreia','Recuperação após o tsunami de 2011','Industrialização do século XIX','Boom imobiliário dos anos 2000'], correct: 0, explanation: 'A Coreia do Sul cresceu de um dos países mais pobres do mundo a uma das maiores economias em apenas 50 anos.', category: 'história', difficulty: 'medium' },
  { question: 'Qual foi o papel dos "chaebols" no desenvolvimento econômico coreano?', options: ['Grandes conglomerados familiares que lideraram a industrialização','Cooperativas agrícolas','Bancos estatais','Empresas estrangeiras'], correct: 0, explanation: 'Chaebols como Samsung, Hyundai e LG foram fundamentais para a industrialização rápida da Coreia do Sul.', category: 'história', difficulty: 'medium' },
  { question: 'Em que ano a Coreia ganhou o Nobel da Paz?', options: ['2000','1998','2002','2005'], correct: 0, explanation: 'Kim Dae-jung recebeu o Prêmio Nobel da Paz em 2000 por seus esforços de reconciliação com a Coreia do Norte.', category: 'história', difficulty: 'medium' },
  { question: 'Qual foi o evento que marcou o início da Hallyu (Onda Coreana) internacionalmente?', options: ['Crise financeira asiática de 1997, que levou a Coreia a exportar cultura','Copa do Mundo de 2002','Jogos Olímpicos de Seul de 1988','Sucesso de Gangnam Style em 2012'], correct: 0, explanation: 'A crise de 1997 forçou a Coreia a investir na exportação de cultura como nova fonte de receita.', category: 'história', difficulty: 'medium' },
  { question: 'Qual foi o papel do Almirante Yi Sun-sin na história coreana?', options: ['Defendeu a Coreia da invasão japonesa com navios tartaruga','Criou o sistema de escrita Hangul','Unificou os Três Reinos','Fundou a Dinastia Joseon'], correct: 0, explanation: 'Yi Sun-sin é um herói nacional que defendeu a Coreia da invasão japonesa (1592) usando os famosos "navios tartaruga".', category: 'história', difficulty: 'medium' },

  // ─── HISTÓRIA — hard ─────────────────────────────────────────────────────────
  { question: 'Qual foi o papel da Coreia na disseminação do Budismo para o Japão?', options: ['Foi o principal intermediário que levou o Budismo da China para o Japão no século VI','Importou o Budismo do Japão no século VIII','Desenvolveu o Budismo independentemente','Converteu o Japão através de guerras'], correct: 0, explanation: 'O reino de Baekje enviou monges e textos budistas ao Japão em 552 d.C., sendo crucial para a disseminação da religião.', category: 'história', difficulty: 'hard' },
  { question: 'Qual foi o Tratado de Ganghwa (1876) e seu impacto na Coreia?', options: ['Tratado desigual que abriu a Coreia ao comércio japonês, iniciando sua subjugação','Acordo de paz após a invasão japonesa de 1592','Tratado de comércio com a China','Acordo de independência com o Japão'], correct: 0, explanation: 'O Tratado de Ganghwa (강화도 조약) foi o primeiro tratado desigual que forçou a abertura comercial da Coreia ao Japão.', category: 'história', difficulty: 'hard' },
  { question: 'Qual foi o significado histórico da Batalha de Salsu (612 d.C.)?', options: ['Vitória de Goguryeo sobre o exército Tang-Sui, um dos maiores do mundo antigo','Unificação da Coreia pelo reino de Silla','Derrota final de Baekje','Expulsão dos mongóis'], correct: 0, explanation: 'Na Batalha de Salsu, Goguryeo destruiu o exército de um milhão de soldados Sui, sendo uma das maiores batalhas da Ásia.', category: 'história', difficulty: 'hard' },
  { question: 'O que foi o Movimento de Reforma Gabo (1894-1896)?', options: ['Série de reformas modernizadoras que aboliram o sistema de castas na Coreia','Revolução armada contra o Japão','Reforma educacional','Modernização militar'], correct: 0, explanation: 'A Reforma Gabo aboliu a escravidão, o sistema de castas e modernizou várias instituições coreanas.', category: 'história', difficulty: 'hard' },
  { question: 'Qual foi o resultado da Conferência de Cairo (1943) em relação à Coreia?', options: ['Declarou que a Coreia seria independente após a guerra','Dividiu a Coreia em zonas de influência','Transferiu a Coreia ao controle americano','Declarou guerra ao Japão'], correct: 0, explanation: 'A Declaração de Cairo (1943) prometeu que a Coreia seria livre e independente "em tempo devido" após a derrota japonesa.', category: 'história', difficulty: 'hard' },
  { question: 'Qual foi o período de Haeban após 1945 na Coreia?', options: ['Período de libertação e caos político entre 1945-1948','Era de prosperidade econômica','Período de reconstrução pós-guerra','Fase de modernização industrial'], correct: 0, explanation: '"Haeban" (해방) significa libertação, referindo-se ao período turbulento entre 1945 e a fundação das duas Coreias em 1948.', category: 'história', difficulty: 'hard' },
  { question: 'Qual empresa coreana foi pioneira na construção naval mundial nos anos 1970?', options: ['Hyundai Heavy Industries','Samsung Heavy Industries','Daewoo Shipbuilding','SK Shipping'], correct: 0, explanation: 'Hyundai Heavy Industries, fundada em 1972, tornou a Coreia líder mundial em construção naval.', category: 'história', difficulty: 'hard' },
  { question: 'O que foi o "Movimento das Velas" de 2016-2017 na Coreia do Sul?', options: ['Protestos que levaram ao impeachment da Presidente Park Geun-hye','Celebração do Ano Novo','Movimento cultural do K-Pop','Festival de lanternas'], correct: 0, explanation: 'O Candlelight Movement levou milhões às ruas pedindo o impeachment de Park Geun-hye, que foi concretizado em 2017.', category: 'história', difficulty: 'hard' },
  { question: 'Qual foi a importância histórica da celadon coreana (goryeo cheongja)?', options: ['Era a porcelana mais refinada do mundo medieval, exportada via Rota da Seda','Foi inventada pelos japoneses e importada pela Coreia','É um tipo de tinta usada na caligrafia','Foi desenvolvida na Dinastia Joseon'], correct: 0, explanation: 'A celadon de Goryeo (séc. X-XIV) era considerada a mais bela do mundo, cobiçada por imperadores chineses.', category: 'história', difficulty: 'hard' },
]

async function main() {
  console.log('Limpando perguntas existentes...')
  await prisma.quizQuestion.deleteMany({})

  console.log(`Inserindo ${questions.length} perguntas...`)

  const BATCH = 50
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH).map((q, j) => ({
      ...q,
      options: q.options,
      position: i + j + 1,
      isActive: true,
    }))
    await prisma.quizQuestion.createMany({ data: batch })
    console.log(`  ${Math.min(i + BATCH, questions.length)}/${questions.length}`)
  }

  const count = await prisma.quizQuestion.count()
  console.log(`\nTotal inserido: ${count} perguntas`)

  const byCategory = await prisma.quizQuestion.groupBy({ by: ['category'], _count: { id: true } })
  byCategory.forEach(c => console.log(`  ${c.category}: ${c._count.id}`))
}

main().catch(console.error).finally(() => prisma.$disconnect())
