import type { ArchiveHub } from './types'

export const productionsNetworkHubs: ArchiveHub[] = [
    {
        slug: 'doramas-tvn',
        kind: 'productions',
        title: 'Doramas coreanos da tvN',
        shortTitle: 'Doramas tvN',
        description: 'Descubra os melhores doramas coreanos produzidos e exibidos pela tvN, o canal de cabo mais prestigioso da Coreia do Sul.',
        intro: [
            'A tvN (tv N) é o canal de cabo mais premiado da Coreia e responsável por alguns dos maiores fenômenos do K-Drama moderno. Desde "Secret Garden" até "Crash Landing on You", a tvN definiu o padrão criativo da indústria.',
            'Com produção de alta qualidade, elencos estrelados e roteiros originais, os doramas da tvN costumam liderar audiências a cabo e gerar buzz global. O canal é frequentemente associado a romances sofisticados, thrillers e dramas de prestígio.',
            'Este hub reúne produções coreanas exibidas ou produzidas pela tvN catalogadas no HallyuHub, com páginas de elenco, sinopse e contexto em português.',
        ],
        keywords: ['doramas tvN', 'kdramas tvN', 'doramas canal tvN', 'melhores doramas tvN', 'tvN korea dramas'],
        faq: [
            { question: 'O que é a tvN coreana?', answer: 'A tvN é um canal de cabo premium sul-coreano pertencente ao grupo CJ ENM. É conhecida por produções de alta qualidade e é o canal de entretenimento mais assistido a cabo na Coreia.' },
            { question: 'Quais são os maiores hits da tvN?', answer: 'Alguns dos maiores sucessos da tvN incluem "Crash Landing on You", "Mr. Sunshine", "Signal", "Reply 1988", "Chicago Typewriter" e "Goblin". O canal tem histórico de produções aclamadas.' },
            { question: 'A tvN tem doramas disponíveis no Brasil?', answer: 'Muitos doramas da tvN estão disponíveis em plataformas de streaming no Brasil, como Netflix, Viki e Prime Video. A disponibilidade varia por título e região.' },
            { question: 'Qual é a diferença entre tvN e emissoras abertas como SBS?', answer: 'A tvN é canal pago e tem mais liberdade criativa, orçamentos maiores e público adulto como alvo. SBS, KBS e MBC são emissoras abertas com foco em audiência familiar ampla.' },
        ],
    },
    {
        slug: 'doramas-sbs',
        kind: 'productions',
        title: 'Doramas coreanos da SBS',
        shortTitle: 'Doramas SBS',
        description: 'Os melhores doramas coreanos da SBS, uma das maiores emissoras abertas da Coreia do Sul, com décadas de produções icônicas.',
        intro: [
            'A SBS (Seoul Broadcasting System) é uma das três grandes emissoras abertas da Coreia do Sul e tem no currículo alguns dos dramas mais assistidos da história da TV coreana.',
            'Com exibição em horário nobre e audiência massiva, os doramas SBS costumam ter elencos consagrados, produções de alto orçamento e histórias que vão de romances a thrillers políticos. A emissora estreou talentos como Lee Min-ho, Song Hye-kyo e Park Bo-gum.',
            'Este hub organiza as produções da SBS catalogadas no HallyuHub para que você encontre elenco, sinopse e contexto editorial de cada título.',
        ],
        keywords: ['doramas SBS', 'kdramas SBS', 'séries coreanas SBS', 'melhores doramas SBS', 'SBS korea dramas'],
        faq: [
            { question: 'O que é a SBS?', answer: 'A SBS (Seoul Broadcasting System) é uma das principais emissoras abertas da Coreia do Sul. Fundada em 1991, é conhecida por novelas, doramas, reality shows e programas de variedade de grande audiência.' },
            { question: 'Quais são os maiores doramas da SBS?', answer: 'A SBS tem clássicos como "Boys Over Flowers", "Heirs", "Pinocchio", "Doctors", "My Love from the Star" e "The King 2 Hearts". A emissora tem tradição em romances de sucesso.' },
            { question: 'Doramas da SBS têm quantos episódios?', answer: 'Doramas de horário nobre da SBS costumam ter entre 16 e 32 episódios. Dramas familiares e diários podem ter mais de 50 episódios.' },
            { question: 'Doramas da SBS estão disponíveis online?', answer: 'Muitos títulos estão no Viki, Netflix, Prime Video e outras plataformas. Disponibilidade varia por título e região.' },
        ],
    },
    {
        slug: 'doramas-mbc',
        kind: 'productions',
        title: 'Doramas coreanos da MBC',
        shortTitle: 'Doramas MBC',
        description: 'Doramas coreanos da MBC, emissora pioneira da Coreia com décadas de clássicos, romances e produções históricas.',
        intro: [
            'A MBC (Munhwa Broadcasting Corporation) é uma das emissoras mais antigas e respeitadas da Coreia do Sul, com longa tradição em doramas de qualidade que marcaram gerações de espectadores.',
            'Do melodrama clássico ao romance moderno, passando por dramas históricos e thrillers, a MBC tem um catálogo extenso que inclui produções que ajudaram a popularizar o K-Drama no mundo. Atores como So Ji-sub, Kim Tae-hee e Jung Il-woo estrelaram produções marcantes da emissora.',
            'Este hub reúne produções da MBC catalogadas no HallyuHub com páginas de elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas MBC', 'kdramas MBC', 'séries coreanas MBC', 'melhores doramas MBC', 'MBC korea drama'],
        faq: [
            { question: 'O que é a MBC coreana?', answer: 'A MBC (Munhwa Broadcasting Corporation) é uma emissora pública de televisão da Coreia do Sul, fundada em 1961. É uma das três grandes emissoras abertas junto com KBS e SBS.' },
            { question: 'Quais são os maiores doramas da MBC?', answer: 'A MBC tem clássicos como "Princess Returning Pearl", "Jewel in the Palace", "Coffee Prince", "Queen Seondeok" e "Personal Taste". A emissora tem forte tradição em saeguk (dramas históricos).' },
            { question: 'Qual é a diferença entre MBC e SBS?', answer: 'Ambas são emissoras abertas de horário nobre. A MBC tem mais tradição em dramas históricos e melodramas, enquanto a SBS é conhecida por romances modernos e thrillers com apelo jovem.' },
            { question: 'Doramas da MBC estão no streaming?', answer: 'Vários títulos estão disponíveis em plataformas como Viki, Netflix e Prime Video. Títulos clássicos podem ter disponibilidade mais limitada fora da Coreia.' },
        ],
    },
    {
        slug: 'doramas-kbs',
        kind: 'productions',
        title: 'Doramas coreanos da KBS',
        shortTitle: 'Doramas KBS',
        description: 'Os melhores doramas coreanos da KBS, emissora pública da Coreia do Sul com o maior catálogo de dramas da televisão coreana.',
        intro: [
            'A KBS (Korea Broadcasting System) é a emissora pública nacional da Coreia e a maior produtora de conteúdo televisivo do país. Com dois canais de programação aberta — KBS1 e KBS2 — o catálogo da emissora é imenso e cobre décadas de produção.',
            'Os dramas da KBS2 são especialmente reconhecidos por romances familiares e tramas acessíveis, enquanto a KBS1 tem mais produção voltada para educação, notícias e conteúdo institucional. Títulos como "Winter Sonata", "Full House" e "Descendants of the Sun" são marcos da KBS.',
            'Este hub reúne produções da KBS (KBS1 e KBS2) catalogadas no HallyuHub com informações de elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas KBS', 'kdramas KBS', 'doramas KBS2', 'séries coreanas KBS', 'KBS korea drama'],
        faq: [
            { question: 'O que é a KBS?', answer: 'A KBS (Korea Broadcasting System) é a emissora pública nacional da Coreia do Sul, fundada em 1927. Opera os canais KBS1 e KBS2, e é a maior emissora do país por volume de produção.' },
            { question: 'Qual a diferença entre KBS1 e KBS2?', answer: 'KBS2 é o canal de entretenimento principal, lar dos doramas populares. KBS1 tem perfil mais informativo, com notícias, documentários e programas educativos.' },
            { question: 'Quais são os maiores doramas da KBS?', answer: 'Clássicos como "Winter Sonata", "Full House", "Boys Over Flowers" (parte na KBS2), "Descendants of the Sun" e "Fight My Way" são destaques da KBS.' },
            { question: 'Doramas da KBS têm acesso online?', answer: 'Muitos títulos da KBS estão disponíveis no Viki, Netflix e plataformas asiáticas. Títulos mais antigos podem ter disponibilidade limitada fora da Coreia.' },
        ],
    },
    {
        slug: 'doramas-jtbc',
        kind: 'productions',
        title: 'Doramas coreanos da JTBC',
        shortTitle: 'Doramas JTBC',
        description: 'Os melhores doramas coreanos da JTBC, o canal de cabo que se tornou referência em produções adultas, dramas de prestígio e histórias ousadas.',
        intro: [
            'A JTBC é um canal de cabo sul-coreano fundado em 2011 que se tornou rapidamente referência em K-Dramas de prestígio. Com foco em histórias adultas, roteiros ousados e produções cinematográficas, a JTBC consolidou seu espaço ao lado da tvN como os canais de cabo mais influentes do país.',
            'Títulos como "The World of the Married", "My Mister", "Itaewon Class", "Sky Castle" e "Snowdrop" mostram o alcance da JTBC: dramas que geram debate nacional, quebram recordes e são exportados para plataformas globais.',
            'Este hub organiza produções da JTBC catalogadas no HallyuHub com elenco, sinopse e contexto editorial em português.',
        ],
        keywords: ['doramas JTBC', 'kdramas JTBC', 'séries coreanas JTBC', 'melhores doramas JTBC', 'JTBC korea drama'],
        faq: [
            { question: 'O que é a JTBC?', answer: 'A JTBC é um canal de cabo sul-coreano pertencente ao grupo JoongAng, lançado em 2011. Ficou conhecida por dramas adultos de alta qualidade e coberturas jornalísticas impactantes.' },
            { question: 'Quais são os maiores doramas da JTBC?', answer: 'Destaques incluem "The World of the Married" (recorde de audiência a cabo), "My Mister", "Itaewon Class", "Sky Castle", "Snowdrop" e "Juvenile Justice".' },
            { question: 'A JTBC é parecida com a tvN?', answer: 'Ambas são canais de cabo premium com perfil adulto e produções de prestígio. A JTBC tende a temas mais polêmicos e sociais; a tvN tem mais foco em romance sofisticado e fantasia.' },
            { question: 'Doramas da JTBC estão no Netflix?', answer: 'Muitos títulos da JTBC têm distribuição internacional via Netflix, incluindo "Itaewon Class", "Juvenile Justice" e "The World of the Married".' },
        ],
    },
    {
        slug: 'doramas-tving',
        kind: 'productions',
        title: 'Doramas coreanos no TVING',
        shortTitle: 'Doramas TVING',
        description: 'Doramas originais e exclusivos do TVING, a principal plataforma de streaming coreana com produções de alta qualidade.',
        intro: [
            'O TVING é a principal plataforma de streaming da Coreia do Sul, operada pelo grupo CJ ENM (o mesmo da tvN e Mnet). Com crescimento acelerado, o TVING passou a investir pesado em produções originais que competem com Netflix e Disney+ em qualidade.',
            'Exclusivos do TVING incluem títulos como "Yumi\'s Cells", "Semantic Error" e produções que misturam K-Pop, romance e thriller com estética moderna. A plataforma é referência para quem acompanha o K-Drama diretamente na fonte.',
            'Este hub organiza produções do TVING catalogadas no HallyuHub com informações de elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas TVING', 'kdramas TVING', 'TVING originais', 'streaming coreano TVING', 'TVING k-drama'],
        faq: [
            { question: 'O que é o TVING?', answer: 'O TVING é a maior plataforma de streaming da Coreia do Sul, pertencente ao grupo CJ ENM. Opera com assinatura e tem catálogo de doramas, variedades, filmes e conteúdo ao vivo.' },
            { question: 'TVING tem acesso fora da Coreia?', answer: 'O TVING tem expansão limitada fora da Ásia. No Brasil, o acesso direto é restrito. Conteúdo TVING costuma chegar ao Viki e outras plataformas com licenciamento internacional.' },
            { question: 'TVING é relacionado à tvN?', answer: 'Sim. Ambos pertencem ao grupo CJ ENM. O TVING funciona como o braço streaming do grupo, transmitindo conteúdo ao vivo da tvN e produzindo exclusivos digitais.' },
            { question: 'Quais são os melhores originais do TVING?', answer: '"Yumi\'s Cells", "Semantic Error" e adaptações de webtoon são destaques do TVING. A plataforma investe em histórias de nicho e romance LGBTQ+.' },
        ],
    },
    {
        slug: 'doramas-ocn',
        kind: 'productions',
        title: 'Doramas coreanos da OCN',
        shortTitle: 'Doramas OCN',
        description: 'Doramas da OCN, o canal de cabo especializado em thriller, ação, crime e sobrenatural com produções de alta intensidade.',
        intro: [
            'A OCN (On Cinema Network) é um canal de cabo sul-coreano do grupo CJ ENM especializado em conteúdo de gênero: thriller, ação, crime, sobrenatural e horror. Se os outros canais dominam o romance, a OCN domina a adrenalina.',
            'Com séries como "Voice", "Tunnel", "Signal" e "Watcher", a OCN construiu uma identidade própria baseada em roteiros sombrios, investigações complexas e protagonistas que enfrentam os limites da moral. É o destino certo para quem prefere suspense a romance.',
            'Este hub reúne produções da OCN catalogadas no HallyuHub com elenco, sinopse e contexto editorial em português.',
        ],
        keywords: ['doramas OCN', 'kdramas OCN', 'OCN thriller coreano', 'doramas policial OCN', 'OCN crime drama'],
        faq: [
            { question: 'O que é a OCN?', answer: 'A OCN (On Cinema Network) é um canal de cabo coreano do grupo CJ ENM especializado em filmes, thrillers, ação e horror. Seus doramas são conhecidos por histórias de crime, policial e suspense.' },
            { question: 'Quais são os maiores doramas da OCN?', answer: 'Destaques incluem "Voice", "Tunnel", "Signal", "Watcher" e "Save Me". A OCN é referência em K-Dramas de crime e suspense.' },
            { question: 'OCN é indicado para quem gosta de thriller?', answer: 'Sim. A OCN é o canal ideal para fãs de thriller, investigação e ação. As produções costumam ser mais sombrias e adultas do que os dramas de romance das outras emissoras.' },
            { question: 'Doramas da OCN estão disponíveis no streaming?', answer: 'Vários títulos estão no Viki e outros serviços asiáticos. A distribuição internacional pode ser menor que canais como tvN e JTBC.' },
        ],
    },
    {
        slug: 'doramas-ena',
        kind: 'productions',
        title: 'Doramas coreanos da ENA',
        shortTitle: 'Doramas ENA',
        description: 'Doramas da ENA, o canal que revelou "Extraordinary Attorney Woo" e se tornou referência em produções emocionantes e únicas.',
        intro: [
            'A ENA é um canal de cabo sul-coreano do grupo SK Broadband que ganhou reconhecimento global em 2022 quando "Extraordinary Attorney Woo" ("A Advogada Extraordinária Woo") se tornou um fenômeno mundial no Netflix.',
            'Antes chamado de Channel A (depois da cisão, o canal ENA e Channel A são entidades separadas), a ENA passou a ser vista como um canal de produções emocionantes com personagens únicos e histórias que abordam representatividade e diferença. A ascensão do canal mostra que o K-Drama não está limitado às grandes emissoras.',
            'Este hub organiza produções da ENA catalogadas no HallyuHub com elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas ENA', 'kdramas ENA', 'ENA canal coreano', 'Extraordinary Attorney Woo canal', 'doramas ENA korea'],
        faq: [
            { question: 'O que é o canal ENA coreano?', answer: 'A ENA é um canal de cabo sul-coreano do grupo SK Broadband. Ganhou notoriedade internacional em 2022 com "Extraordinary Attorney Woo", que se tornou um dos dramas coreanos mais assistidos globalmente no Netflix.' },
            { question: 'A ENA é um canal grande na Coreia?', answer: 'A ENA é menor que tvN, JTBC, SBS e MBC, mas seu perfil mudou radicalmente após o sucesso global de "Extraordinary Attorney Woo". O canal passou a receber mais atenção de produtoras e roteiristas.' },
            { question: 'Quais outros doramas vieram da ENA?', answer: '"Crash Course in Romance" e alguns thrillers são produções associadas à ENA. O catálogo ainda é menor que os grandes canais, mas crescendo em qualidade e variedade.' },
            { question: 'Doramas da ENA estão no Netflix?', answer: '"Extraordinary Attorney Woo" chegou ao Netflix e foi um hit global. Outros títulos podem ter distribuição mais limitada em plataformas internacionais.' },
        ],
    },
]
