import type { ArchiveHub } from './types'

export const productionsYearHubs: ArchiveHub[] = [
    {
        slug: 'doramas-coreanos-2026',
        kind: 'productions',
        year: 2026,
        title: 'Doramas coreanos 2026',
        shortTitle: 'K-Dramas 2026',
        description: 'Os melhores doramas coreanos lançados em 2026 com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            '2026 chega com novas apostas da indústria coreana em plataformas globais, continuando a expansão do K-Drama para audiências internacionais.',
            'Este hub reúne produções coreanas de 2026 cadastradas no HallyuHub, com páginas em português para entender elenco, sinopse e onde assistir.',
        ],
        keywords: ['doramas 2026', 'kdramas 2026', 'doramas coreanos novos 2026', 'melhores doramas 2026'],
        faq: [
            { question: 'Onde assistir doramas coreanos em 2026?', answer: 'Os principais doramas de 2026 estão disponíveis no Netflix, Disney+, Amazon Prime Video, Viki e Kocowa, dependendo do título e da sua região.' },
            { question: 'Quais são os doramas mais esperados de 2026?', answer: 'O HallyuHub lista os principais lançamentos de doramas de 2026 com avaliações, sinopse e links para elenco completo.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2025',
        kind: 'productions',
        year: 2025,
        title: 'Doramas coreanos 2025',
        shortTitle: 'K-Dramas 2025',
        description: 'Os melhores doramas coreanos lançados em 2025 com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            '2025 continua sendo um ano prolífico para os K-Dramas, com lançamentos em plataformas globais como Netflix, Disney+ e Amazon Prime.',
            'Este hub reúne produções coreanas de 2025 cadastradas no HallyuHub, com páginas em português para entender elenco, sinopse e onde assistir.',
        ],
        keywords: ['doramas 2025', 'kdramas 2025', 'doramas coreanos novos 2025', 'melhores doramas 2025'],
        faq: [
            { question: 'Onde assistir doramas coreanos em 2025?', answer: 'Os principais doramas de 2025 estão disponíveis no Netflix, Disney+, Amazon Prime Video, Viki e Kocowa, dependendo do título e da sua região.' },
            { question: 'Quais são os doramas mais esperados de 2025?', answer: 'O HallyuHub lista os principais lançamentos de doramas de 2025 com avaliações, sinopse e links para elenco completo.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2024',
        kind: 'productions',
        year: 2024,
        title: 'Doramas coreanos 2024',
        shortTitle: 'K-Dramas 2024',
        description: 'Os melhores doramas coreanos lançados em 2024 com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            '2024 foi um ano marcante para os K-Dramas, com lançamentos que conquistaram audiências globais e debutaram nas listas de mais assistidos do mundo.',
            'Este hub reúne produções coreanas de 2024 cadastradas no HallyuHub, com páginas em português para entender elenco, sinopse e onde assistir.',
        ],
        keywords: ['doramas 2024', 'kdramas 2024', 'melhores doramas 2024', 'doramas coreanos 2024'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2024?', answer: 'O HallyuHub lista os principais doramas de 2024 ordenados por avaliação, com sinopse e links para elenco completo em português.' },
            { question: 'Onde assistir os doramas de 2024?', answer: 'A maioria dos doramas de 2024 está disponível no Netflix, Disney+ e Viki. Alguns títulos também estão no Amazon Prime Video.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2023',
        kind: 'productions',
        year: 2023,
        title: 'Doramas coreanos 2023',
        shortTitle: 'K-Dramas 2023',
        description: 'Os melhores doramas coreanos lançados em 2023 com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            '2023 trouxe doramas que marcaram gerações de fãs e confirmaram a consolidação dos K-Dramas como um dos gêneros mais consumidos do mundo.',
            'Este hub reúne produções coreanas de 2023 cadastradas no HallyuHub, com páginas em português para entender elenco, sinopse e onde assistir.',
        ],
        keywords: ['doramas 2023', 'kdramas 2023', 'melhores doramas 2023', 'doramas coreanos 2023'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2023?', answer: 'O HallyuHub lista os principais doramas de 2023 ordenados por avaliação, incluindo títulos que foram destaque no Netflix e outras plataformas.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2022',
        kind: 'productions',
        year: 2022,
        title: 'Doramas coreanos 2022',
        shortTitle: 'K-Dramas 2022',
        description: 'Os melhores doramas coreanos lançados em 2022 com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            '2022 foi o primeiro ano pós-pandemia com produção plena de K-Dramas, trazendo títulos que rapidamente se tornaram clássicos modernos do gênero.',
            'Este hub reúne produções coreanas de 2022 cadastradas no HallyuHub, com páginas em português para entender elenco, sinopse e onde assistir.',
        ],
        keywords: ['doramas 2022', 'kdramas 2022', 'melhores doramas 2022', 'doramas coreanos 2022', 'dorama 2022', 'dorameiros 2022'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2022?', answer: 'O HallyuHub lista os principais doramas de 2022 com avaliação, sinopse e elenco completo em português para ajudar você a escolher o próximo.' },
            { question: 'Onde assistir doramas de 2022?', answer: 'A maioria dos doramas de 2022 está disponível no Netflix, Viki, Disney+ e Amazon Prime Video. A disponibilidade varia por região.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2021',
        kind: 'productions',
        year: 2021,
        title: 'Doramas coreanos 2021',
        shortTitle: 'K-Dramas 2021',
        description: 'Os melhores doramas coreanos de 2021, o ano em que Squid Game e outros títulos levaram o K-Drama ao topo das listas globais.',
        intro: [
            '2021 foi um ano histórico para o K-Drama. "Squid Game" se tornou o maior lançamento da história do Netflix e colocou a Coreia no topo da cultura pop global como nunca antes.',
            'Além do fenômeno da Netflix, 2021 trouxe títulos aclamados em romance, thriller e fantasia que consolidaram a geração de artistas que dominaria o cenário nos anos seguintes.',
            'Este hub reúne produções coreanas de 2021 catalogadas no HallyuHub, com páginas de elenco, sinopse e contexto em português para dorameiros e dorameiras.',
        ],
        keywords: ['doramas 2021', 'kdramas 2021', 'melhores doramas 2021', 'doramas coreanos 2021', 'squid game 2021', 'dorameiros 2021'],
        faq: [
            { question: 'Quais foram os maiores doramas de 2021?', answer: 'Além de "Squid Game", 2021 teve "Hometown Cha-Cha-Cha", "My Name", "Hellbound", "Vincenzo" e "Mouse" entre os títulos mais comentados.' },
            { question: 'Onde assistir doramas de 2021?', answer: 'Grande parte dos títulos de 2021 está no Netflix, Viki e Prime Video. "Squid Game" é exclusivo do Netflix.' },
            { question: 'Por que 2021 foi especial para o K-Drama?', answer: '"Squid Game" quebrou recordes mundiais de streaming e levou o K-Drama a audiências que nunca tinham assistido uma produção coreana.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2020',
        kind: 'productions',
        year: 2020,
        title: 'Doramas coreanos 2020',
        shortTitle: 'K-Dramas 2020',
        description: 'Os melhores doramas coreanos de 2020, ano de "Crash Landing on You" e outros fenômenos que conquistaram o mundo.',
        intro: [
            '2020 ficou marcado pela pandemia — e pelos doramas. Com o mundo em casa, títulos como "Crash Landing on You", "It\'s Okay to Not Be Okay" e "Start-Up" se tornaram fenômenos que introduziram milhões de novos dorameiros e dorameiras ao K-Drama.',
            'A produção coreana manteve ritmo intenso mesmo com restrições, e plataformas de streaming como Netflix e Viki registraram crescimento recorde de audiência para conteúdo asiático.',
            'Este hub reúne os doramas coreanos de 2020 catalogados no HallyuHub com informações de elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas 2020', 'kdramas 2020', 'melhores doramas 2020', 'crash landing on you', 'doramas coreanos 2020', 'dorameiros 2020'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2020?', answer: '"Crash Landing on You", "It\'s Okay to Not Be Okay", "Start-Up", "Stranger Season 2" e "The King: Eternal Monarch" foram os grandes destaques de 2020.' },
            { question: 'Por que 2020 foi importante para o K-Drama?', answer: 'A pandemia fez as pessoas em todo o mundo procurarem conteúdo em casa. K-Dramas como "Crash Landing on You" viralizaram e introduziram o gênero a novos públicos.' },
            { question: 'Onde assistir doramas de 2020?', answer: 'Títulos de 2020 estão disponíveis no Netflix, Viki e Amazon Prime Video. "Crash Landing on You" é disponível via Netflix.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2019',
        kind: 'productions',
        year: 2019,
        title: 'Doramas coreanos 2019',
        shortTitle: 'K-Dramas 2019',
        description: 'Os melhores doramas coreanos de 2019 com sinopse, elenco e avaliações em português.',
        intro: [
            '2019 foi um ano forte para o K-Drama, com títulos que se tornaram referências no gênero e lançaram atores e atrizes que seguem no topo da indústria.',
            '"Hotel Del Luna", "Crash Landing on You" (estreou em dezembro de 2019), "Romance is a Bonus Book" e "Arthdal Chronicles" foram alguns dos títulos mais comentados do ano.',
            'Este hub reúne produções coreanas de 2019 cadastradas no HallyuHub com elenco, sinopse e contexto editorial para dorameiros e dorameiras.',
        ],
        keywords: ['doramas 2019', 'kdramas 2019', 'melhores doramas 2019', 'doramas coreanos 2019', 'hotel del luna', 'dorameiros 2019'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2019?', answer: '"Hotel Del Luna", "Arthdal Chronicles", "Romance is a Bonus Book" e "Angel\'s Last Mission: Love" estão entre os mais assistidos e bem avaliados de 2019.' },
            { question: 'Onde assistir doramas de 2019?', answer: 'Doramas de 2019 estão disponíveis no Netflix, Viki e Amazon Prime Video. Disponibilidade varia por título e região.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2018',
        kind: 'productions',
        year: 2018,
        title: 'Doramas coreanos 2018',
        shortTitle: 'K-Dramas 2018',
        description: 'Os melhores doramas coreanos de 2018, ano de "My Mister", "Mr. Sunshine" e outros clássicos modernos.',
        intro: [
            '2018 produziu alguns dos doramas mais aclamados da história: "My Mister" é considerado por muitos fãs o melhor K-Drama já feito, e "Mr. Sunshine" foi um épico histórico que redefiniu o padrão de produção da tvN.',
            'O ano também marcou o crescimento da influência da JTBC e o início de uma nova fase do K-Drama, com roteiros mais complexos e produções cinematográficas.',
            'Este hub reúne produções coreanas de 2018 catalogadas no HallyuHub com elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas 2018', 'kdramas 2018', 'melhores doramas 2018', 'my mister dorama', 'mr sunshine dorama', 'doramas coreanos 2018'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2018?', answer: '"My Mister", "Mr. Sunshine", "Are You Human Too?", "Mother" e "Memories of the Alhambra" são os grandes destaques de 2018.' },
            { question: '"My Mister" é de 2018?', answer: 'Sim. "My Mister" estreou na JTBC em 2018 e com IU e Lee Sun-kyun. É amplamente considerado um dos melhores K-Dramas já produzidos.' },
            { question: 'Onde assistir doramas de 2018?', answer: 'Doramas de 2018 estão no Netflix, Viki e Amazon Prime Video. "My Mister" está disponível no Netflix em várias regiões.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2017',
        kind: 'productions',
        year: 2017,
        title: 'Doramas coreanos 2017',
        shortTitle: 'K-Dramas 2017',
        description: 'Os melhores doramas coreanos de 2017 com sinopse, elenco completo e avaliações em português.',
        intro: [
            '2017 marcou o início de uma era de ouro para os K-Dramas, com "Goblin" — lançado no final de 2016 e concluído em 2017 — dominando conversas e sendo exportado globalmente.',
            'O ano também trouxe "Strong Woman Do Bong-soon", "Chicago Typewriter", "The K2" e outros títulos que consolidaram novos atores como favoritos dos fãs internacionais.',
            'Este hub reúne produções coreanas de 2017 cadastradas no HallyuHub com elenco, sinopse e contexto para dorameiros e dorameiras.',
        ],
        keywords: ['doramas 2017', 'kdramas 2017', 'melhores doramas 2017', 'goblin dorama', 'doramas coreanos 2017', 'dorameiras 2017'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2017?', answer: '"Strong Woman Do Bong-soon", "Chicago Typewriter", "While You Were Sleeping" e "Tunnel" são destaques de 2017. "Goblin" foi concluído em 2017 também.' },
            { question: 'Onde assistir doramas de 2017?', answer: 'Doramas de 2017 estão no Netflix, Viki e Amazon Prime Video. Disponibilidade varia por título e região.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2016',
        kind: 'productions',
        year: 2016,
        title: 'Doramas coreanos 2016',
        shortTitle: 'K-Dramas 2016',
        description: 'Os melhores doramas coreanos de 2016, ano de "Descendants of the Sun" e o início do boom global do K-Drama.',
        intro: [
            '"Descendants of the Sun" estreou em 2016 e foi um dos primeiros doramas a ser simultâneo na Coreia e na China, gerando um fenômeno continental que ajudou a impulsionar o Hallyu para novos mercados.',
            'O ano também produziu "Goblin" (estreou em dezembro de 2016), "Signal", "Uncontrollably Fond" e outros títulos que marcaram a memória de toda uma geração de fãs.',
            'Este hub organiza produções coreanas de 2016 no HallyuHub com elenco, sinopse e contexto editorial.',
        ],
        keywords: ['doramas 2016', 'kdramas 2016', 'descendants of the sun dorama', 'melhores doramas 2016', 'doramas coreanos 2016', 'goblin 2016'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2016?', answer: '"Descendants of the Sun", "Goblin" (início), "Signal", "Doctors" e "W" são os grandes destaques de 2016.' },
            { question: '"Descendants of the Sun" é de 2016?', answer: 'Sim. O drama com Song Joong-ki e Song Hye-kyo estreou na KBS2 em fevereiro de 2016 e tornou-se um fenômeno na Ásia.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2015',
        kind: 'productions',
        year: 2015,
        title: 'Doramas coreanos 2015',
        shortTitle: 'K-Dramas 2015',
        description: 'Os melhores doramas coreanos de 2015 com sinopse, elenco e contexto em português.',
        intro: [
            '2015 foi marcado por "Kill Me Heal Me", "Oh My Ghost", "Healer" e "Cheese in the Trap" — títulos que lançaram ou consolidaram carreiras de atores que seguem como favoritos da fandom.',
            'O ano também viu o crescimento das transmissões simultâneas para a China e o Sudeste Asiático, expandindo o alcance do K-Drama além da comunidade de fãs dedicados.',
            'Este hub reúne produções coreanas de 2015 catalogadas no HallyuHub.',
        ],
        keywords: ['doramas 2015', 'kdramas 2015', 'melhores doramas 2015', 'kill me heal me dorama', 'doramas coreanos 2015', 'dorameiros 2015'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2015?', answer: '"Kill Me Heal Me", "Oh My Ghost", "Healer" e "Hyde Jekyll, Me" são alguns dos destaques de 2015.' },
            { question: 'Onde assistir doramas de 2015?', answer: 'Doramas de 2015 estão disponíveis no Viki, Netflix (alguns títulos) e Amazon Prime Video. Títulos mais antigos podem ter disponibilidade menor.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2014',
        kind: 'productions',
        year: 2014,
        title: 'Doramas coreanos 2014',
        shortTitle: 'K-Dramas 2014',
        description: 'Os melhores doramas coreanos de 2014 com sinopse, elenco e avaliações em português.',
        intro: [
            '2014 entregou "My Love from the Star" — um dorama que rompeu barreiras culturais e ajudou a consolidar o K-Drama como fenômeno de massa na China, sudeste asiático e além.',
            '"Pinocchio", "It\'s Okay, That\'s Love", "The Heirs" e "Angel Eyes" completam uma safra memorável que marcou a geração de fãs que cresceu com o K-Drama.',
            'Este hub reúne produções coreanas de 2014 catalogadas no HallyuHub.',
        ],
        keywords: ['doramas 2014', 'kdramas 2014', 'my love from the star dorama', 'melhores doramas 2014', 'doramas coreanos 2014', 'the heirs 2014'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2014?', answer: '"My Love from the Star", "Pinocchio", "The Heirs" e "It\'s Okay, That\'s Love" são os grandes destaques de 2014.' },
            { question: '"My Love from the Star" é de 2014?', answer: 'Estreou no final de 2013 e foi concluído em 2014. É um dos doramas mais famosos da história, com Kim Soo-hyun e Jun Ji-hyun.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2013',
        kind: 'productions',
        year: 2013,
        title: 'Doramas coreanos 2013',
        shortTitle: 'K-Dramas 2013',
        description: 'Os melhores doramas coreanos de 2013 com sinopse, elenco e avaliações em português.',
        intro: [
            '2013 foi um ano prolífico para o K-Drama, com títulos que se tornaram clássicos do gênero e influenciaram produções por anos. "Heirs/The Inheritors", "You Who Came from the Stars" (início) e "Master\'s Sun" estão entre os destaques.',
            'A parceria entre canais como tvN, KBS e MBC com plataformas de streaming asiáticas começou a mostrar resultados nesse período, aumentando o alcance internacional dos doramas.',
            'Este hub reúne produções coreanas de 2013 catalogadas no HallyuHub.',
        ],
        keywords: ['doramas 2013', 'kdramas 2013', 'melhores doramas 2013', 'the heirs 2013', 'doramas coreanos 2013', 'masters sun dorama'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2013?', answer: '"Master\'s Sun", "The Heirs", "I Hear Your Voice", "Gu Family Book" e "Nine: Nine Time Travels" são destaques de 2013.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2012',
        kind: 'productions',
        year: 2012,
        title: 'Doramas coreanos 2012',
        shortTitle: 'K-Dramas 2012',
        description: 'Os melhores doramas coreanos de 2012 com sinopse, elenco e avaliações em português.',
        intro: [
            '2012 trouxe "Faith", "Nice Guy", "Arang and the Magistrate" e o premiado "Answer Me 1997", da tvN — um marco que mostrou o potencial dos canais de cabo em produzir histórias que rivalizavam com as emissoras abertas.',
            'O ano foi importante para a formação da identidade dos canais premium e o início de uma nova fase criativa no K-Drama.',
            'Este hub reúne produções coreanas de 2012 catalogadas no HallyuHub.',
        ],
        keywords: ['doramas 2012', 'kdramas 2012', 'melhores doramas 2012', 'doramas coreanos 2012', 'answer me 1997 dorama'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2012?', answer: '"Faith", "Nice Guy", "Arang and the Magistrate", "I Do, I Do" e "Answer Me 1997" são destaques de 2012.' },
        ],
    },
    {
        slug: 'doramas-coreanos-2010',
        kind: 'productions',
        year: 2010,
        title: 'Doramas coreanos 2010',
        shortTitle: 'K-Dramas 2010',
        description: 'Os melhores doramas coreanos de 2010, clássicos que moldaram o K-Drama moderno.',
        intro: [
            '2010 foi o ano de "Secret Garden", um dorama que se tornou cultural na Coreia e consolidou Hyun Bin e Ha Ji-won como estrelas de primeira grandeza. Junto com "My Girlfriend is a Gumiho" e "Baker King", formou uma das safras mais queridas da memória do K-Drama.',
            'Esses títulos representam uma geração de doramas que equilibrava humor, romance, fantasia e melodrama de forma que capturou audiências dentro e fora da Coreia.',
            'Este hub reúne produções coreanas de 2010 catalogadas no HallyuHub.',
        ],
        keywords: ['doramas 2010', 'kdramas 2010', 'secret garden dorama', 'doramas classicos 2010', 'doramas coreanos 2010', 'dorameiros classicos'],
        faq: [
            { question: 'Quais foram os melhores doramas de 2010?', answer: '"Secret Garden", "My Girlfriend is a Gumiho", "Baker King, Kim Tak-goo" e "Playful Kiss" são destaques de 2010.' },
            { question: 'Onde assistir doramas de 2010?', answer: 'Clássicos de 2010 estão disponíveis no Viki e algumas plataformas asiáticas. "Secret Garden" pode estar no Netflix em alguns países.' },
        ],
    },
]
